import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../../theme";

export const styles = StyleSheet.create({
  disabled: { opacity: 0.42 },
  errorText: {
    color: colors.red,
    ...typeScale.body,
  },
  fullContentCentered: {
    alignItems: "center",
    flex: 1,
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 0,
    padding: spacing.md,
  },
  fullContentFooter: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderTopColor: colors.borderSoft,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: controlSize.touch,
    paddingHorizontal: spacing.sm,
  },
  fullContentFooterText: {
    color: colors.textMuted,
    flex: 1,
    ...typeScale.caption,
  },
  fullContentHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: layoutSize.header,
    paddingHorizontal: spacing.sm,
  },
  fullContentHeaderIcon: {
    alignItems: "center",
    flexShrink: 0,
    height: controlSize.compact,
    justifyContent: "center",
    width: controlSize.compact,
  },
  fullContentHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  fullContentMarkdown: {
    padding: spacing.md,
    paddingBottom: spacing.xl,
  },
  fullContentMeta: {
    color: colors.textMuted,
    ...typeScale.caption,
    fontVariant: ["tabular-nums"],
  },
  fullContentRawHorizontal: {
    flexGrow: 0,
    padding: spacing.sm,
  },
  fullContentRawText: {
    color: "#D3D7DE",
    ...typeScale.code,
    fontFamily: Platform.select({
      android: "monospace",
      default: "Courier",
    }),
  },
  fullContentTitle: {
    color: colors.text,
    ...typeScale.title,
    fontWeight: typeWeight.semibold,
  },
  fullContentViewer: {
    backgroundColor: colors.background,
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  fullContentViewport: {
    backgroundColor: colors.code,
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  headerIcon: {
    alignItems: "center",
    borderRadius: radii.large,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  largeContentActions: {
    gap: spacing.xxs,
    minWidth: 0,
    width: "100%",
  },
  largeContentButton: {
    alignItems: "center",
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    flexDirection: "row",
    gap: spacing.compact,
    minHeight: controlSize.compact,
    minWidth: 0,
    paddingHorizontal: spacing.xs,
  },
  largeContentButtonText: {
    color: colors.textMuted,
    flex: 1,
    minWidth: 0,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  largeContentControl: {
    gap: spacing.compact,
    minWidth: 0,
    paddingTop: spacing.xxs,
    width: "100%",
  },
  largeContentPageButton: {
    alignItems: "center",
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    height: controlSize.compact,
    justifyContent: "center",
    width: controlSize.compact,
  },
  largeContentPager: {
    flexDirection: "row",
    gap: spacing.xxs,
    justifyContent: "flex-end",
  },
  menuNotice: {
    color: colors.textMuted,
    ...typeScale.body,
    paddingVertical: spacing.xs,
  },
  pressed: { opacity: 0.68 },
  turnMetaText: {
    color: colors.textMuted,
    ...typeScale.caption,
  },
});
