//! Claude Code's own formats in user text (`AgentProvider::user_text_cleaner`):
//! records Claude Code stores as user-role input but the user never typed
//! (slash-command and local-command records, task notifications, the local
//! command caveat, interruption markers, the compaction summary) and the
//! system reminders it appends to a typed message. The host already leaves
//! most of them out of its history; this covers every other place user text
//! is shown (thread-list previews, live items).

use agent_core::user_text::{CleanedText, UserTextCleaner};

/// Cleans Claude Code's formats out of user text.
pub struct ClaudeUserText;

/// Openings of a record Claude Code stores as user input.
const CONTEXT_PREFIXES: &[&str] = &[
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-stdout>",
    "<local-command-stderr>",
    "<local-command-caveat>",
    "<task-notification>",
    "<system-reminder>",
    "Caveat: The messages below were generated by the user while running local commands",
    "[Request interrupted by user",
    "This session is being continued from a previous conversation",
];

const REMINDER_OPEN: &str = "<system-reminder>";
const REMINDER_CLOSE: &str = "</system-reminder>";

impl UserTextCleaner for ClaudeUserText {
    fn clean(&self, text: &str) -> CleanedText {
        let trimmed = text.trim_start();
        if CONTEXT_PREFIXES
            .iter()
            .any(|prefix| trimmed.starts_with(prefix))
        {
            return CleanedText::ModelContext;
        }
        if !text.contains(REMINDER_OPEN) {
            return CleanedText::Unchanged;
        }
        let authored = without_reminders(text);
        let authored = authored.trim();
        if authored.is_empty() {
            CleanedText::ModelContext
        } else {
            CleanedText::Authored(authored.to_owned())
        }
    }
}

/// The text without complete `<system-reminder>…</system-reminder>` blocks.
fn without_reminders(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(start) = rest.find(REMINDER_OPEN) {
        let Some(end) = rest[start..].find(REMINDER_CLOSE) else {
            break;
        };
        out.push_str(&rest[..start]);
        rest = &rest[start + end + REMINDER_CLOSE.len()..];
    }
    out.push_str(rest);
    out
}

#[cfg(test)]
mod tests {
    use agent_core::user_text::display_text;

    use super::ClaudeUserText;

    #[test]
    fn hides_claude_code_records_and_appended_reminders() {
        for record in [
            "<command-name>/clear</command-name>\n<command-message>clear</command-message>",
            "<local-command-stdout>ok</local-command-stdout>",
            "Caveat: The messages below were generated by the user while running local commands. DO NOT respond.",
            "[Request interrupted by user for tool use]",
            "<system-reminder>Only a reminder</system-reminder>",
        ] {
            assert_eq!(display_text(record, &ClaudeUserText), None, "{record}");
        }
        assert_eq!(
            display_text(
                "Fix the test\n\n<system-reminder>Context</system-reminder>",
                &ClaudeUserText
            )
            .as_deref(),
            Some("Fix the test")
        );
        assert_eq!(
            display_text("Explain <div> tags", &ClaudeUserText).as_deref(),
            Some("Explain <div> tags")
        );
    }
}
