import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  rawLink: { color: colors.accent, ...typeScale.label, fontWeight: typeWeight.semibold },
  disabled: { opacity: 0.42 },
  fieldLabel: { color: colors.textMuted, ...typeScale.label, marginTop: spacing.xxs },
  fieldInput: {
    minHeight: touchTarget,
    color: colors.text,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.outline,
    paddingHorizontal: spacing.md,
    ...typeScale.body,
  },
  errorText: { color: colors.red, ...typeScale.body },
  sheetActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.inputInset,
    marginTop: spacing.inputInset,
  },
  secondaryButton: {
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  secondaryButtonText: { color: colors.text, fontWeight: typeWeight.semibold },
  primaryButton: {
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    backgroundColor: colors.primary,
  },
  primaryButtonText: { color: colors.onPrimary, fontWeight: typeWeight.semibold },
  connectionEditor: { minWidth: 0 },
  connectionEditorForm: { paddingVertical: spacing.sm, gap: spacing.xs },
  connectionIdentityFields: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  connectionRow: { minHeight: layoutSize.row, paddingVertical: spacing.xs, gap: spacing.xxs },
  connectionMiniButton: {
    width: touchTarget,
    height: touchTarget,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
  },
  connectionActionMenuAnchor: { width: touchTarget, height: touchTarget, flexShrink: 0 },
  connectionEmojiInput: {
    width: 52,
    minHeight: controlSize.touch,
    color: colors.text,
    backgroundColor: colors.surface,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.xs,
    ...typeScale.emoji,
  },
  connectionStateRow: {
    minHeight: 18,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.compact,
    marginTop: spacing.xxs,
  },
  connectionStateIcon: {
    width: 12,
    height: 12,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  connectionStateDot: { width: 7, height: 7, borderRadius: radii.pill },
  connectionStateText: {
    minWidth: 0,
    flexShrink: 1,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  connectionDiagnostic: {
    gap: spacing.xs,
    marginLeft: controlSize.touch,
    padding: spacing.inputInset,
    borderRadius: radii.medium,
    backgroundColor: colors.errorContainer,
  },
  connectionDiagnosticHeader: { flexDirection: "row", alignItems: "flex-start", gap: spacing.xs },
  connectionDiagnosticSummary: { flex: 1, color: colors.onErrorContainer, ...typeScale.label },
  connectionDiagnosticMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingLeft: spacing.lg,
  },
  connectionDiagnosticTime: { color: colors.textMuted, ...typeScale.caption },
  connectionDiagnosticRaw: {
    color: colors.onErrorContainer,
    ...typeScale.code,
    fontFamily: Platform.select({ android: "monospace", default: "Courier" }),
    paddingLeft: spacing.lg,
  },
});
