import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  connectionSheetContent: { gap: spacing.xs },
  connectionSheetScroll: { width: "100%" },
  disabled: { opacity: 0.42 },
  errorText: {
    color: colors.red,
    ...typeScale.body,
  },
  fieldInput: {
    backgroundColor: colors.surfaceContainerLow,
    borderColor: colors.outline,
    borderRadius: radii.medium,
    borderWidth: 1,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    ...typeScale.body,
  },
  fieldLabel: {
    color: colors.textMuted,
    ...typeScale.label,
    marginTop: spacing.xxs,
  },
  flex: { flex: 1 },
  pairingActionStack: {
    gap: spacing.xs,
    marginTop: spacing.optical,
  },
  pairingBack: {
    alignItems: "center",
    borderRadius: radii.pill,
    height: controlSize.regular,
    justifyContent: "center",
    width: controlSize.regular,
  },
  pairingBody: {
    gap: spacing.md,
    paddingBottom: spacing.optical,
  },
  pairingCode: {
    color: colors.text,
    fontFamily: Platform.select({
      android: "monospace",
      default: "Courier",
    }),
  },
  pairingEmojiInput: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.xs,
    width: 52,
    ...typeScale.emoji,
    textAlign: "center",
  },
  pairingEndpoint: {
    color: colors.textMuted,
    ...typeScale.label,
    flex: 1,
  },
  pairingError: {
    alignItems: "center",
    backgroundColor: colors.errorContainer,
    borderRadius: radii.medium,
    flexDirection: "row",
    gap: spacing.xs,
    padding: spacing.inputInset,
  },
  pairingHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xxs,
    justifyContent: "space-between",
    minHeight: layoutSize.header,
  },
  pairingHeaderTitle: {
    color: colors.text,
    flex: 1,
    minWidth: 0,
    ...typeScale.heading,
  },
  pairingHeroIcon: {
    alignItems: "center",
    alignSelf: "center",
    backgroundColor: colors.primaryContainer,
    borderRadius: radii.medium,
    height: controlSize.touch,
    justifyContent: "center",
    width: controlSize.touch,
  },
  pairingHint: {
    color: colors.textMuted,
    ...typeScale.body,
    paddingHorizontal: spacing.xs,
    textAlign: "center",
  },
  pairingIdentityFields: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  pairingIdentityRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  pairingLead: {
    color: colors.text,
    ...typeScale.heading,
    paddingHorizontal: spacing.sm,
    textAlign: "center",
  },
  pairingMetaText: {
    color: colors.textMuted,
    flex: 1,
    minWidth: 0,
    ...typeScale.label,
  },
  pairingNameInput: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    color: colors.text,
    flex: 1,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
    ...typeScale.title,
  },
  pairingPrimaryAction: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.pill,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  pairingPrimaryText: {
    color: colors.onPrimary,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  pairingReviewCard: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.large,
    gap: spacing.inputInset,
    padding: spacing.sm,
  },
  pairingSafety: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.compact,
    justifyContent: "center",
    paddingTop: spacing.xxs,
  },
  pairingSafetyText: {
    color: colors.textDim,
    ...typeScale.label,
    flexShrink: 1,
  },
  pairingSecondaryAction: {
    alignItems: "center",
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.pill,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  pairingSecondaryText: {
    color: colors.text,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  pairingServerMeta: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: layoutSize.metadataRow,
  },
  pairingSuccess: {
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.lg,
  },
  pairingSuccessIcon: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.pill,
    height: layoutSize.row,
    justifyContent: "center",
    width: 60,
  },
  pairingSuccessTitle: {
    color: colors.text,
    ...typeScale.heading,
    textAlign: "center",
  },
  pairingTextAction: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xxs,
    justifyContent: "center",
    minHeight: controlSize.regular,
  },
  pairingTextActionLabel: {
    color: colors.textMuted,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
});
