import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  disabled: { opacity: 0.42 },
  connectionSheetScroll: { width: "100%" },
  connectionSheetContent: { gap: spacing.xs },
  pairingHeader: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xxs,
  },
  pairingHeaderTitle: { flex: 1, minWidth: 0, color: colors.text, ...typeScale.heading },
  pairingBack: {
    width: controlSize.regular,
    height: controlSize.regular,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.pill,
  },
  pairingBody: { gap: spacing.md, paddingBottom: spacing.optical },
  pairingHeroIcon: {
    width: controlSize.touch,
    height: controlSize.touch,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    backgroundColor: colors.primaryContainer,
  },
  pairingLead: {
    color: colors.text,
    ...typeScale.heading,
    textAlign: "center",
    paddingHorizontal: spacing.sm,
  },
  pairingHint: {
    color: colors.textMuted,
    ...typeScale.body,
    textAlign: "center",
    paddingHorizontal: spacing.xs,
  },
  pairingCode: {
    color: colors.text,
    fontFamily: Platform.select({ android: "monospace", default: "Courier" }),
  },
  pairingActionStack: { gap: spacing.xs, marginTop: spacing.optical },
  pairingPrimaryAction: {
    minHeight: touchTarget,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
  },
  pairingPrimaryText: {
    color: colors.onPrimary,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  pairingSecondaryAction: {
    minHeight: touchTarget,
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceRaised,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
  },
  pairingSecondaryText: { color: colors.text, ...typeScale.body, fontWeight: typeWeight.semibold },
  pairingTextAction: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xxs,
  },
  pairingTextActionLabel: {
    color: colors.textMuted,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  pairingSafety: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.compact,
    paddingTop: spacing.xxs,
  },
  pairingSafetyText: { color: colors.textDim, ...typeScale.label, flexShrink: 1 },
  pairingError: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    padding: spacing.inputInset,
    borderRadius: radii.medium,
    backgroundColor: colors.errorContainer,
  },
  pairingReviewCard: {
    gap: spacing.inputInset,
    padding: spacing.sm,
    borderRadius: radii.large,
    backgroundColor: colors.surfaceContainerLow,
  },
  pairingIdentityRow: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  pairingIdentityFields: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  pairingEmojiInput: {
    width: 52,
    minHeight: touchTarget,
    color: colors.text,
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    paddingHorizontal: spacing.xs,
    ...typeScale.emoji,
    textAlign: "center",
  },
  pairingNameInput: {
    flex: 1,
    minHeight: touchTarget,
    color: colors.text,
    backgroundColor: colors.surfaceRaised,
    borderRadius: radii.medium,
    paddingHorizontal: spacing.sm,
    ...typeScale.title,
  },
  pairingServerMeta: {
    minHeight: layoutSize.metadataRow,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  pairingEndpoint: { color: colors.textMuted, ...typeScale.label, flex: 1 },
  pairingMetaText: { flex: 1, minWidth: 0, color: colors.textMuted, ...typeScale.label },
  pairingSuccess: { alignItems: "center", gap: spacing.sm, paddingVertical: spacing.lg },
  pairingSuccessIcon: {
    width: 60,
    height: layoutSize.row,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primary,
  },
  pairingSuccessTitle: { color: colors.text, ...typeScale.heading, textAlign: "center" },
  fieldLabel: { color: colors.textMuted, ...typeScale.label, marginTop: spacing.xxs },
  fieldInput: {
    minHeight: touchTarget,
    color: colors.text,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.outline,
    paddingHorizontal: spacing.md,
    ...typeScale.body,
  },
  errorText: { color: colors.red, ...typeScale.body },
});
