import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  connectionActionMenuAnchor: {
    flexShrink: 0,
    height: touchTarget,
    width: touchTarget,
  },
  connectionDiagnostic: {
    backgroundColor: colors.errorContainer,
    borderRadius: radii.medium,
    gap: spacing.xs,
    marginLeft: controlSize.touch,
    padding: spacing.inputInset,
  },
  connectionDiagnosticHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.xs,
  },
  connectionDiagnosticMeta: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    paddingLeft: spacing.lg,
  },
  connectionDiagnosticRaw: {
    color: colors.onErrorContainer,
    ...typeScale.code,
    fontFamily: Platform.select({
      android: "monospace",
      default: "Courier",
    }),
    paddingLeft: spacing.lg,
  },
  connectionDiagnosticSummary: {
    color: colors.onErrorContainer,
    flex: 1,
    ...typeScale.label,
  },
  connectionDiagnosticTime: {
    color: colors.textMuted,
    ...typeScale.caption,
  },
  connectionEditor: { minWidth: 0 },
  connectionEditorForm: {
    gap: spacing.xs,
    paddingVertical: spacing.sm,
  },
  connectionEmojiInput: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: 1,
    color: colors.text,
    minHeight: controlSize.touch,
    paddingHorizontal: spacing.xs,
    width: 52,
    ...typeScale.emoji,
  },
  connectionIdentityFields: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  connectionMiniButton: {
    alignItems: "center",
    borderRadius: radii.medium,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  connectionRow: {
    gap: spacing.xxs,
    minHeight: layoutSize.row,
    paddingVertical: spacing.xs,
  },
  connectionStateDot: {
    borderRadius: radii.pill,
    height: 7,
    width: 7,
  },
  connectionStateIcon: {
    alignItems: "center",
    flexShrink: 0,
    height: 12,
    justifyContent: "center",
    width: 12,
  },
  connectionStateRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.compact,
    marginTop: spacing.xxs,
    minHeight: 18,
    minWidth: 0,
  },
  connectionStateText: {
    flexShrink: 1,
    minWidth: 0,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  disabled: { opacity: 0.42 },
  errorText: {
    color: colors.red,
    ...typeScale.body,
  },
  fieldInput: {
    backgroundColor: colors.surfaceContainerLow,
    borderColor: colors.outline,
    borderRadius: radii.medium,
    borderWidth: 1,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    ...typeScale.body,
  },
  fieldLabel: {
    color: colors.textMuted,
    ...typeScale.label,
    marginTop: spacing.xxs,
  },
  flex: { flex: 1 },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.medium,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontWeight: typeWeight.semibold,
  },
  rawLink: {
    color: colors.accent,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: colors.outline,
    borderRadius: radii.medium,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: typeWeight.semibold,
  },
  sheetActions: {
    flexDirection: "row",
    gap: spacing.inputInset,
    justifyContent: "flex-end",
    marginTop: spacing.inputInset,
  },
});
