import type { Personality } from "@codewide/codex-protocol/v0.147.0";
import type { DraftSelection } from "../../data/voice-draft";
import type { VoiceInputRow } from "../../data/workspace-resource-database";
import type { LargePasteEvent } from "../../native/large-paste";
import type { QueuedComposerEdit } from "./composerTypes";
import type { ComposerSendPreference } from "./deliveryMode";
import type { ComposerMarkdownInputHandle } from "./input/ComposerMarkdownInput.types";
import type { ComposerMention } from "./input/composer-mentions";
import type { Thread } from "@codewide/codex-protocol/v0.147.0/v2";
import type { Dispatch, RefObject, SetStateAction } from "react";
import type { ReactNode } from "react";
import { View } from "react-native";
import type { GetTransferAccess } from "../../data/private-transfer";
import type { StoredDraftAttachment } from "../../data/thread-ui-state-types";
import type { TurnControlsValue } from "../../data/turn-controls-types";
import type { VoiceInputController } from "../../data/voice-input-controller";
import type { WorkspaceResourceDatabase } from "../../data/workspace-resource-database";
import type { ActionMenuItem } from "../../ui/ActionMenu";
import type { ComposerAccessoryAction, ComposerMenuPage } from "./composerTypes";
export type ComposerFeatureProps = {
  newChat: boolean;
  workspaceResources: WorkspaceResourceDatabase | null;
  controlsResourceId: string | null;
  cwd: string;
  remoteThread: Thread | null | undefined;
  readOnly: boolean;
  selectedModel: string | null;
  selectedEffort: string | null;
  selectedPersonality: Personality | null;
  selectedPermissions: string | null;
  controlError: string | null;
  onLoadControls: ((cwd: string) => Promise<TurnControlsValue>) | undefined;
  openQuickControlMenu: (_scope: "model-menu" | "permissions-menu") => void;
  closeQuickControlMenu: (_scope: "model-menu" | "permissions-menu") => undefined;
  openControls: (initialPage: ComposerMenuPage) => void;
  selectModel: (model: string, effort: string) => void;
  selectEffort: (effort: string) => void;
  setSelectedPersonality: (value: Personality | null) => void;
  selectPermissions: (permissions: string | null) => void;
  toolContextChips: ReactNode;
  queuedComposerEdit: QueuedComposerEdit | null;
  cancelQueuedComposerEdit: () => void;
  voiceError: string | null;
  queuedComposerEditError: string | null;
  getTransferAccess: GetTransferAccess | undefined;
  composerUploadScope: string;
  attachments: StoredDraftAttachment[];
  getStableTransferAccess: GetTransferAccess;
  removeComposerAttachment: (attachmentId: string) => void;
  composerTrayVisible: boolean;
  useAnchoredComposerMenu: boolean;
  fileAttachmentEnabled: boolean;
  draftConnectionId: string | null;
  draftThreadId: string | null;
  portForwardingConnectionId: string | null;
  openAccessoryAction: (action: ComposerAccessoryAction) => void;
  anchoredComposerActions: ActionMenuItem[];
  dismissComposerKeyboardForOverlay: () => void;
  handleAnchoredComposerAction: (id: string) => void;
  setComposerTrayVisible: Dispatch<SetStateAction<boolean>>;
  voicePhase: "idle" | "starting" | "recording" | "finishing";
  composerScope: string;
  composerInputRef: { current: ComposerMarkdownInputHandle | null };
  pastedAttachmentPending: boolean;
  handleComposerLargePaste: (event: LargePasteEvent) => void;
  draft: string;
  handleComposerTextChange: (nextText: string) => void;
  handleComposerMarkdownChange: (markdown: string) => void;
  draftSelectionRef: { current: DraftSelection };
  pendingVoiceSelection: { start: number; end: number } | null;
  voiceController: VoiceInputController | null;
  searchComposerSuggestions: (query: {
    readonly indicator: "/" | "@";
    readonly text: string;
  }) => Promise<ComposerMention[]>;
  selectComposerMention: (mention: ComposerMention) => void;
  editingQueuedMessage: boolean;
  voiceBackend: "android" | "remote";
  voiceResource: VoiceInputRow | null;
  microphoneButtonRef: RefObject<View | null>;
  voiceRetryAvailable: boolean;
  retryVoice: () => Promise<void>;
  toggleVoice: () => Promise<void>;
  finishVoice: (sendAfter: boolean, preference?: ComposerSendPreference) => Promise<void>;
  microphoneAccess: { granted: boolean; allowCapture: () => boolean };
  sendDisabled: boolean;
  composerDiscardEnabled: boolean;
  queuedComposerEditBusy: boolean;
  discardComposer: () => void;
  steerComposer: () => void;
  activatePrimaryAction: () => void;
  deliveryActions: ActionMenuItem[];
  handleDeliveryAction: (id: string) => void;
  stoppingResponse: boolean;
  threadLifecycleActive: boolean;
  currentTurnId: string | null;
};
