import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  section: {
    marginTop: spacing.md,
    paddingTop: spacing.sm,
    gap: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
  },
  toggleRow: {
    minHeight: layoutSize.row,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  iconShell: {
    width: controlSize.regular,
    height: controlSize.regular,
    borderRadius: radii.medium,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceRaised,
  },
  toggleCopy: { flex: 1, minWidth: 0 },
  title: { color: colors.text, ...typeScale.title },
  subtitle: { marginTop: spacing.optical, color: colors.textMuted, ...typeScale.label },
  notice: { color: colors.textMuted, ...typeScale.body },
  error: { color: colors.red, ...typeScale.body },
  collecting: {
    minHeight: controlSize.touch,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs },
  metricTile: {
    width: "48%",
    flexGrow: 1,
    minWidth: 130,
    padding: spacing.sm,
    gap: spacing.optical,
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainerLow,
  },
  metricLabel: { color: colors.textMuted, ...typeScale.label },
  metricValue: {
    color: colors.text,
    ...typeScale.heading,
    fontWeight: typeWeight.semibold,
    fontVariant: ["tabular-nums"],
  },
  metricDetail: { color: colors.textDim, ...typeScale.label, fontVariant: ["tabular-nums"] },
  chartCard: {
    padding: spacing.sm,
    gap: spacing.sm,
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainerLow,
  },
  chartHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  chartTitle: { color: colors.text, ...typeScale.title },
  chartSubtitle: { marginTop: spacing.optical, color: colors.textDim, ...typeScale.caption },
  legend: { flexDirection: "row", flexWrap: "wrap", justifyContent: "flex-end", gap: spacing.xs },
  legendItem: { flexDirection: "row", alignItems: "center", gap: spacing.xxs },
  legendDot: { width: 7, height: 7, borderRadius: radii.pill },
  legendLabel: { color: colors.textMuted, ...typeScale.caption },
  sparkline: { height: layoutSize.row, overflow: "hidden" },
  chartEmpty: { color: colors.textDim, ...typeScale.label },
  memoryRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  memoryBreakdown: { gap: spacing.xs },
  memoryLabel: { color: colors.textMuted, ...typeScale.label, fontVariant: ["tabular-nums"] },
  experimentCard: {
    padding: spacing.sm,
    gap: spacing.sm,
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainerLow,
  },
  experimentHeader: { flexDirection: "row", alignItems: "flex-start", gap: spacing.sm },
  experimentHeaderCopy: { flex: 1, minWidth: 0 },
  diagnosticsButtonRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: spacing.xs,
  },
  diagnosticActionRow: { alignItems: "flex-end", gap: spacing.xs },
  experimentRow: {
    minHeight: layoutSize.row,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.borderSoft,
    paddingTop: spacing.xs,
  },
  experimentCopy: { flex: 1, minWidth: 0 },
  experimentTitle: { color: colors.text, ...typeScale.body, fontWeight: typeWeight.semibold },
  experimentDescription: { color: colors.textMuted, ...typeScale.label },
  smallButton: {
    minHeight: controlSize.compact,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.medium,
  },
  smallButtonPressed: { opacity: 0.72 },
  smallButtonText: { color: colors.text, ...typeScale.label },
  abButton: {
    minWidth: controlSize.compact,
    minHeight: controlSize.compact,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xs,
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainerHigh,
  },
  abButtonText: { color: colors.text, ...typeScale.label, fontWeight: typeWeight.semibold },
  buttonDisabled: { opacity: 0.5 },
  stageRow: {
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  stageLabel: { flex: 1, color: colors.textMuted, ...typeScale.label },
  stageValue: { color: colors.text, ...typeScale.label, fontVariant: ["tabular-nums"] },
  counterWrap: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm },
  counterText: { color: colors.textDim, ...typeScale.caption, fontVariant: ["tabular-nums"] },
  resultCard: {
    padding: spacing.sm,
    gap: spacing.xs,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.amber,
    backgroundColor: colors.surfaceContainerLow,
  },
  resultHeadline: {
    color: colors.text,
    ...typeScale.heading,
    fontWeight: typeWeight.semibold,
    fontVariant: ["tabular-nums"],
  },
  footnote: { color: colors.textDim, ...typeScale.caption },
});
