import { StyleSheet } from "react-native";
import { colors, controlSize, radii, spacing, touchTarget, typeScale } from "../../../theme";

export const styles = StyleSheet.create({
  activeButton: { backgroundColor: colors.surfaceRaised },
  browserNotice: {
    backgroundColor: colors.surface,
    color: colors.textMuted,
    minHeight: 22,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    ...typeScale.label,
  },
  button: {
    alignItems: "center",
    borderRadius: radii.small,
    height: controlSize.regular,
    justifyContent: "center",
    width: controlSize.regular,
  },
  content: {
    flex: 1,
    minHeight: 0,
  },
  contentRow: { flexDirection: "row" },
  contentRowReverse: { flexDirection: "row-reverse" },
  devTools: {
    backgroundColor: "#202124",
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  devToolsError: {
    alignItems: "center",
    backgroundColor: "#202124",
    bottom: 0,
    gap: spacing.sm,
    justifyContent: "center",
    left: 0,
    padding: spacing.lg,
    position: "absolute",
    right: 0,
    top: 0,
  },
  devToolsLoading: {
    alignItems: "center",
    backgroundColor: "#202124",
    bottom: 0,
    gap: spacing.sm,
    justifyContent: "center",
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  devToolsPane: {
    backgroundColor: "#202124",
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  devToolsStatus: {
    color: colors.textMuted,
    textAlign: "center",
    ...typeScale.body,
  },
  disabled: { opacity: 0.35 },
  divider: {
    alignItems: "center",
    backgroundColor: "transparent",
    flexShrink: 0,
    justifyContent: "center",
  },
  dividerHandle: {
    backgroundColor: colors.border,
    borderRadius: radii.compact,
  },
  dividerHandleHorizontal: {
    height: 2,
    width: 48,
  },
  dividerHandleVertical: {
    height: controlSize.touch,
    width: 2,
  },
  dividerHidden: { display: "none" },
  dividerHorizontal: {
    height: 10,
    width: "100%",
  },
  dividerVertical: {
    height: "100%",
    width: 10,
  },
  loading: {
    inset: 0,
    position: "absolute",
  },
  pressed: { opacity: 0.7 },
  root: {
    backgroundColor: colors.background,
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  targetPane: {
    flexShrink: 0,
    minHeight: 0,
    minWidth: 0,
  },
  targetPaneClosed: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  targetPaneUndocked: {
    height: 1,
    opacity: 0,
    position: "absolute",
    width: 1,
  },
  toolbar: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.borderSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: spacing.optical,
    minHeight: touchTarget,
    paddingHorizontal: spacing.xs,
    zIndex: 2,
  },
  toolbarEditing: { paddingHorizontal: spacing.xs },
  webView: {
    backgroundColor: colors.background,
    flex: 1,
  },
});
