mod activity_metrics_live;
pub mod agent;
pub mod auth;
pub mod build_shelf;
pub mod content;
pub mod device_tls;
pub mod diagnostics;
pub mod dictation;
mod direct_access;
mod file_revisions;
pub mod file_uploads;
pub mod files;
pub mod global_supervisor_limits;
pub mod host_identity;
pub mod identity;
pub mod image_previews;
pub mod managed_runtime;
pub mod media;
pub mod pairing_qr;
pub mod port_inventory;
pub mod ports;
pub mod projects;
pub mod relay;
pub mod remote_inputs;
pub mod runtime_host;
pub mod secure_store;
pub mod server;
mod session_authority;
pub mod state_migration;
pub mod store;
pub mod sync;
mod sync_live;
mod sync_pending;
pub mod telemetry;
pub mod terminal;
pub mod thread_patch;
mod thread_pins;
pub mod thread_view;
pub mod tunnels;
pub mod usage;
mod user_message_projection;
pub mod vcs;
pub mod workspaces;

/// The JSON-RPC agent transports, re-exported for the companion and its hosts.
pub use agent_transport as upstream;
