import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
} from "../../theme";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: colors.background,
  },
  header: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: spacing.xs,
    paddingRight: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  headerButton: {
    width: touchTarget,
    height: touchTarget,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.pill,
  },
  tabScroll: {
    flex: 1,
    minWidth: 0,
  },
  tabList: {
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  tab: {
    minHeight: controlSize.compact,
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: radii.small,
    backgroundColor: colors.surfaceHover,
  },
  activeTab: { backgroundColor: colors.surfaceRaised },
  tabSelect: {
    minWidth: controlSize.regular,
    flex: 1,
    alignSelf: "stretch",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingLeft: spacing.sm,
  },
  tabText: {
    flexShrink: 1,
    color: colors.textMuted,
    ...typeScale.label,
  },
  activeTabText: { color: colors.text },
  tabClose: {
    width: controlSize.compact,
    height: controlSize.compact,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.small,
  },
  newTab: {
    width: controlSize.regular,
    height: controlSize.regular,
    marginRight: spacing.xs,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.small,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: radii.pill,
  },
  statusLive: { backgroundColor: colors.green },
  statusError: { backgroundColor: colors.red },
  statusIdle: { backgroundColor: colors.textDim },
  terminalPane: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  terminal: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: colors.background,
  },
  connecting: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
  },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    backgroundColor: colors.errorContainer,
  },
  errorText: {
    flex: 1,
    color: colors.red,
    ...typeScale.label,
  },
  empty: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    padding: spacing.lg,
  },
  emptyTitle: {
    color: colors.textMuted,
    ...typeScale.body,
  },
  createButton: {
    minHeight: touchTarget,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radii.medium,
    backgroundColor: colors.accent,
  },
  createButtonText: {
    color: colors.onPrimary,
    ...typeScale.body,
  },
  pressed: { opacity: 0.72 },
  disabled: { opacity: 0.4 },
});
