import type { Thread } from "@codewide/codex-protocol/v0.147.0/v2";
import type { TurnUsageProjection } from "@codewide/sync-client";
import type { Dispatch, SetStateAction } from "react";
import type { AccountRateLimitsDatabase } from "../../../data/account-rate-limits-database";
import type { ThreadChatModel } from "../../../data/thread-chat-model";
import type { ThreadForkOptions } from "../../../data/thread-fork";
import type { ThreadHistoryModel } from "../../../data/thread-history-model";
import type { ThreadListServer } from "../../connections/connectionPresentation";
import type { ThreadListItem } from "../../threadList/threadListTypes";

/** Display state and actions accepted by the conversation header. */
export type ConversationHeaderProps = {
  compact: boolean;
  onBack: (() => void) | undefined;
  thread: ThreadListItem;
  threadChatModel: ThreadChatModel | null;
  draftConnectionId: string | null;
  draftThreadId: string | null;
  historyActivityModel: ThreadHistoryModel | null;
  historyActivityResourceId: string | null;
  server: ThreadListServer | undefined;
  cwd: string;
  newChat: boolean;
  threadSearchVisible: boolean;
  closeThreadSearch: () => void;
  setThreadSearchVisible: Dispatch<SetStateAction<boolean>>;
  remoteThread: Thread | null | undefined;
  currentUsage: TurnUsageProjection | null;
  sessionCompactionCount: number | null;
  accountRateLimitsDatabase: AccountRateLimitsDatabase | null;
  onRefreshAccountRateLimits: (() => Promise<unknown>) | undefined;
  readOnly: boolean;
  archived: boolean;
  pinned: boolean;
  dismissComposerKeyboardForOverlay: () => void;
  openThreadRename: () => void;
  onTogglePin: (() => Promise<void>) | undefined;
  onUnarchive: (() => Promise<void>) | undefined;
  onArchive: (() => Promise<void>) | undefined;
  onCompact: (() => Promise<void>) | undefined;
  onFork: ((options: ThreadForkOptions) => Promise<void>) | undefined;
  deleteThread: (() => Promise<void>) | undefined;
};
