import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    minHeight: 0,
    backgroundColor: colors.background,
  },
  header: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.compact,
    paddingHorizontal: spacing.xs,
    backgroundColor: colors.surface,
  },
  iconButton: {
    width: controlSize.regular,
    height: controlSize.regular,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainer,
  },
  headerTitle: {
    flex: 1,
    minWidth: 80,
  },
  title: {
    color: colors.text,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  subtitleRow: {
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
  },
  subtitle: {
    flexShrink: 1,
    color: colors.textMuted,
    ...typeScale.label,
  },
  documentStatus: {
    flexShrink: 1,
    color: colors.textDim,
    ...typeScale.label,
  },
  reviewToolbar: {
    minHeight: controlSize.touch,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.xxs,
    backgroundColor: "#111214",
  },
  modeSwitch: {
    flexDirection: "row",
    backgroundColor: "#090A0C",
    borderRadius: radii.pill,
    padding: spacing.xxs,
  },
  modeButton: {
    minWidth: controlSize.compact,
    minHeight: controlSize.compact,
    paddingVertical: spacing.xxs,
    paddingHorizontal: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.pill,
  },
  modeButtonSelected: { backgroundColor: "#26292E" },
  modeButtonText: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  modeButtonTextSelected: {
    color: colors.text,
    fontWeight: typeWeight.semibold,
  },
  wrapButton: {
    minHeight: controlSize.compact,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: radii.pill,
    backgroundColor: "#17191C",
  },
  wrapButtonSelected: { backgroundColor: "#242A33" },
  wrapButtonText: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  wrapButtonTextSelected: {
    color: colors.text,
    fontWeight: typeWeight.semibold,
  },
  attachButton: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.medium,
    backgroundColor: colors.surfaceContainer,
  },
  attachButtonReady: { backgroundColor: colors.surfaceContainerHigh },
  attachButtonCompact: {
    minHeight: controlSize.regular,
    width: controlSize.regular,
    paddingHorizontal: 0,
    justifyContent: "center",
  },
  attachButtonText: {
    color: colors.text,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  workspace: {
    flex: 1,
    minHeight: 0,
    flexDirection: "row",
    position: "relative",
  },
  editorPane: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: "#0B0C0E",
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  muted: { color: colors.textMuted },
  commentStrip: {
    flexGrow: 0,
    maxHeight: 48,
    backgroundColor: "#111214",
  },
  commentStripContent: {
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  commentChip: {
    maxWidth: "100%",
    minHeight: controlSize.compact,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    backgroundColor: colors.surfaceContainerHighest,
    borderRadius: radii.pill,
  },
  commentChipLocation: {
    color: colors.accent,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  commentChipBody: {
    flexShrink: 1,
    color: colors.text,
    ...typeScale.label,
  },
  disabled: { opacity: 0.38 },
});
