import { Platform, StyleSheet } from "react-native";

import { colors, radii, spacing, touchTarget, typeScale } from "../../theme";

export const requestStyles = StyleSheet.create({
  action: {
    alignItems: "center",
    borderRadius: radii.medium,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
  },
  actionLabel: typeScale.body,
  actions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.xs,
    justifyContent: "flex-end",
  },
  booleanChoices: { flexDirection: "row", gap: spacing.xs },
  card: {
    backgroundColor: colors.warningContainer,
    borderRadius: radii.selected,
    gap: spacing.xxs,
    marginHorizontal: spacing.xs,
    marginTop: spacing.optical,
    padding: spacing.xs,
  },
  choice: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.medium,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: spacing.xxs,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
  },
  choiceSelected: { backgroundColor: colors.accentMuted, borderColor: colors.accent },
  choices: { gap: spacing.xs },
  code: {
    ...typeScale.code,
    backgroundColor: colors.code,
    borderRadius: radii.small,
    color: colors.text,
    fontFamily: Platform.select({ android: "monospace", default: "Courier" }),
    padding: spacing.xs,
  },
  destructiveAction: { backgroundColor: colors.errorContainer },
  disabled: { opacity: 0.45 },
  error: { ...typeScale.label, color: colors.red },
  embeddedCard: { marginHorizontal: 0 },
  field: { gap: spacing.xxs },
  input: {
    ...typeScale.body,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.small,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
  },
  link: { color: colors.accent, textDecorationLine: "underline" },
  pendingText: { ...typeScale.caption, color: colors.amber },
  primaryAction: { backgroundColor: colors.primary },
  primaryActionLabel: { color: colors.onPrimary },
  secondaryAction: { backgroundColor: colors.secondaryContainer },
  title: { flex: 1 },
  titleRow: { alignItems: "center", flexDirection: "row", gap: spacing.xs },
});
