// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(companion_swift_ffiFFI)
import companion_swift_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_companion_swift_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_companion_swift_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCompanionSwiftFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol CoreHostProtocol: AnyObject, Sendable {

    func appServerConnection()  -> FfiAppServerConnection

    /**
     * Creates a time-bounded device pairing link.
     * # Errors
     * Returns an adapter error when Relay is unavailable or state cannot persist.
     */
    func createPairing() throws  -> FfiPairing

    func devices()  -> [FfiDeviceStatus]

    /**
     * Finds local Codex homes with a reachable App Server endpoint.
     *
     * The default and currently selected homes remain visible while offline,
     * so the macOS host can explain and recover the unavailable state.
     *
     * # Errors
     * Returns when the user's home directory cannot be inspected safely.
     */
    func discoverAppServers(homeDirectory: String) throws  -> [FfiAppServerCandidate]

    /**
     * Returns the current lifecycle and version proof.
     *
     * # Errors
     *
     * Returns an adapter error if another thread poisoned the runtime lock.
     */
    func health() throws  -> FfiRuntimeHealth

    /**
     * Consumes a Relay invitation and starts its outbound adapter.
     * # Errors
     * Returns an adapter error for invalid input, trust, or network failure.
     */
    func pairRelay(relayAddress: String, invitationJson: String) throws  -> FfiRelayStatus

    /**
     * Persists the update checkpoint before Swift terminates the host.
     *
     * # Errors
     *
     * Returns an adapter error if the target is invalid, state persistence
     * fails, or another thread poisoned the runtime lock.
     */
    func prepareForUpdate(targetVersion: String) throws  -> FfiRuntimeHealth

    /**
     * Returns durable Relay configuration and live reachability.
     * # Errors
     * Returns an adapter error when Relay state is invalid or unsafe.
     */
    func relayStatus() throws  -> FfiRelayStatus

    /**
     * Revokes one paired device.
     * # Errors
     * Returns an adapter error when the durable registry cannot be updated.
     */
    func revokeDevice(deviceId: String) throws  -> Bool

    /**
     * Enables or disables the configured Relay adapter.
     * # Errors
     * Returns an adapter error when Relay state cannot be changed durably.
     */
    func setRelayEnabled(enabled: Bool) throws  -> FfiRelayStatus

}
open class CoreHost: CoreHostProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_companion_swift_ffi_fn_clone_corehost(self.handle, $0) }
    }
    /**
     * Opens the shared core in the Swift `LaunchAgent` process.
     *
     * # Errors
     *
     * Returns an adapter error when the state directory cannot be opened,
     * migrated, exclusively locked, or durably checkpointed.
     */
public convenience init(stateDirectory: String, codexHome: String, appVersion: String, hostVersion: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_constructor_corehost_new(
        FfiConverterString.lower(stateDirectory),
        FfiConverterString.lower(codexHome),
        FfiConverterString.lower(appVersion),
        FfiConverterString.lower(hostVersion),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_companion_swift_ffi_fn_free_corehost(handle, $0) }
    }




open func appServerConnection() -> FfiAppServerConnection  {
    return try!  FfiConverterTypeFfiAppServerConnection_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_app_server_connection(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Creates a time-bounded device pairing link.
     * # Errors
     * Returns an adapter error when Relay is unavailable or state cannot persist.
     */
open func createPairing()throws  -> FfiPairing  {
    return try  FfiConverterTypeFfiPairing_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_create_pairing(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func devices() -> [FfiDeviceStatus]  {
    return try!  FfiConverterSequenceTypeFfiDeviceStatus.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_devices(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Finds local Codex homes with a reachable App Server endpoint.
     *
     * The default and currently selected homes remain visible while offline,
     * so the macOS host can explain and recover the unavailable state.
     *
     * # Errors
     * Returns when the user's home directory cannot be inspected safely.
     */
open func discoverAppServers(homeDirectory: String)throws  -> [FfiAppServerCandidate]  {
    return try  FfiConverterSequenceTypeFfiAppServerCandidate.lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_discover_app_servers(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(homeDirectory),uniffiCallStatus
    )
})
}

    /**
     * Returns the current lifecycle and version proof.
     *
     * # Errors
     *
     * Returns an adapter error if another thread poisoned the runtime lock.
     */
open func health()throws  -> FfiRuntimeHealth  {
    return try  FfiConverterTypeFfiRuntimeHealth_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_health(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Consumes a Relay invitation and starts its outbound adapter.
     * # Errors
     * Returns an adapter error for invalid input, trust, or network failure.
     */
open func pairRelay(relayAddress: String, invitationJson: String)throws  -> FfiRelayStatus  {
    return try  FfiConverterTypeFfiRelayStatus_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_pair_relay(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(relayAddress),
        FfiConverterString.lower(invitationJson),uniffiCallStatus
    )
})
}

    /**
     * Persists the update checkpoint before Swift terminates the host.
     *
     * # Errors
     *
     * Returns an adapter error if the target is invalid, state persistence
     * fails, or another thread poisoned the runtime lock.
     */
open func prepareForUpdate(targetVersion: String)throws  -> FfiRuntimeHealth  {
    return try  FfiConverterTypeFfiRuntimeHealth_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_prepare_for_update(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(targetVersion),uniffiCallStatus
    )
})
}

    /**
     * Returns durable Relay configuration and live reachability.
     * # Errors
     * Returns an adapter error when Relay state is invalid or unsafe.
     */
open func relayStatus()throws  -> FfiRelayStatus  {
    return try  FfiConverterTypeFfiRelayStatus_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_relay_status(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

    /**
     * Revokes one paired device.
     * # Errors
     * Returns an adapter error when the durable registry cannot be updated.
     */
open func revokeDevice(deviceId: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_revoke_device(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(deviceId),uniffiCallStatus
    )
})
}

    /**
     * Enables or disables the configured Relay adapter.
     * # Errors
     * Returns an adapter error when Relay state cannot be changed durably.
     */
open func setRelayEnabled(enabled: Bool)throws  -> FfiRelayStatus  {
    return try  FfiConverterTypeFfiRelayStatus_lift(try rustCallWithError(FfiConverterTypeCompanionFfiError_lift) {
        uniffiCallStatus in
    uniffi_companion_swift_ffi_fn_method_corehost_set_relay_enabled(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(enabled),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreHost: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = CoreHost

    public static func lift(_ handle: UInt64) throws -> CoreHost {
        return CoreHost(unsafeFromHandle: handle)
    }

    public static func lower(_ value: CoreHost) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreHost {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: CoreHost, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreHost_lift(_ handle: UInt64) throws -> CoreHost {
    return try FfiConverterTypeCoreHost.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreHost_lower(_ value: CoreHost) -> UInt64 {
    return FfiConverterTypeCoreHost.lower(value)
}




public struct FfiAppServerCandidate: Equatable, Hashable {
    public var id: String
    public var displayName: String
    public var codexHome: String
    public var availability: FfiAppServerAvailability
    public var selected: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, displayName: String, codexHome: String, availability: FfiAppServerAvailability, selected: Bool) {
        self.id = id
        self.displayName = displayName
        self.codexHome = codexHome
        self.availability = availability
        self.selected = selected
    }




}

#if compiler(>=6)
extension FfiAppServerCandidate: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAppServerCandidate: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAppServerCandidate {
        return
            try FfiAppServerCandidate(
                id: FfiConverterString.read(from: &buf),
                displayName: FfiConverterString.read(from: &buf),
                codexHome: FfiConverterString.read(from: &buf),
                availability: FfiConverterTypeFfiAppServerAvailability.read(from: &buf),
                selected: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAppServerCandidate, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.codexHome, into: &buf)
        FfiConverterTypeFfiAppServerAvailability.write(value.availability, into: &buf)
        FfiConverterBool.write(value.selected, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerCandidate_lift(_ buf: RustBuffer) throws -> FfiAppServerCandidate {
    return try FfiConverterTypeFfiAppServerCandidate.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerCandidate_lower(_ value: FfiAppServerCandidate) -> RustBuffer {
    return FfiConverterTypeFfiAppServerCandidate.lower(value)
}


public struct FfiDeviceStatus: Equatable, Hashable {
    public var id: String
    public var name: String
    public var createdAtUnixMs: UInt64
    public var lastSeenAtUnixMs: UInt64
    public var activeConnections: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, createdAtUnixMs: UInt64, lastSeenAtUnixMs: UInt64, activeConnections: UInt32) {
        self.id = id
        self.name = name
        self.createdAtUnixMs = createdAtUnixMs
        self.lastSeenAtUnixMs = lastSeenAtUnixMs
        self.activeConnections = activeConnections
    }




}

#if compiler(>=6)
extension FfiDeviceStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDeviceStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDeviceStatus {
        return
            try FfiDeviceStatus(
                id: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                createdAtUnixMs: FfiConverterUInt64.read(from: &buf),
                lastSeenAtUnixMs: FfiConverterUInt64.read(from: &buf),
                activeConnections: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiDeviceStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterUInt64.write(value.createdAtUnixMs, into: &buf)
        FfiConverterUInt64.write(value.lastSeenAtUnixMs, into: &buf)
        FfiConverterUInt32.write(value.activeConnections, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDeviceStatus_lift(_ buf: RustBuffer) throws -> FfiDeviceStatus {
    return try FfiConverterTypeFfiDeviceStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDeviceStatus_lower(_ value: FfiDeviceStatus) -> RustBuffer {
    return FfiConverterTypeFfiDeviceStatus.lower(value)
}


public struct FfiPairing: Equatable, Hashable {
    public var link: String
    public var expiresAtUnixMs: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(link: String, expiresAtUnixMs: UInt64) {
        self.link = link
        self.expiresAtUnixMs = expiresAtUnixMs
    }




}

#if compiler(>=6)
extension FfiPairing: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPairing: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPairing {
        return
            try FfiPairing(
                link: FfiConverterString.read(from: &buf),
                expiresAtUnixMs: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: FfiPairing, into buf: inout [UInt8]) {
        FfiConverterString.write(value.link, into: &buf)
        FfiConverterUInt64.write(value.expiresAtUnixMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPairing_lift(_ buf: RustBuffer) throws -> FfiPairing {
    return try FfiConverterTypeFfiPairing.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPairing_lower(_ value: FfiPairing) -> RustBuffer {
    return FfiConverterTypeFfiPairing.lower(value)
}


public struct FfiRelayStatus: Equatable, Hashable {
    public var configured: Bool
    public var enabled: Bool
    public var connection: String
    public var publicEndpoint: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(configured: Bool, enabled: Bool, connection: String, publicEndpoint: String?) {
        self.configured = configured
        self.enabled = enabled
        self.connection = connection
        self.publicEndpoint = publicEndpoint
    }




}

#if compiler(>=6)
extension FfiRelayStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRelayStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRelayStatus {
        return
            try FfiRelayStatus(
                configured: FfiConverterBool.read(from: &buf),
                enabled: FfiConverterBool.read(from: &buf),
                connection: FfiConverterString.read(from: &buf),
                publicEndpoint: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRelayStatus, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.configured, into: &buf)
        FfiConverterBool.write(value.enabled, into: &buf)
        FfiConverterString.write(value.connection, into: &buf)
        FfiConverterOptionString.write(value.publicEndpoint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRelayStatus_lift(_ buf: RustBuffer) throws -> FfiRelayStatus {
    return try FfiConverterTypeFfiRelayStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRelayStatus_lower(_ value: FfiRelayStatus) -> RustBuffer {
    return FfiConverterTypeFfiRelayStatus.lower(value)
}


public struct FfiRuntimeHealth: Equatable, Hashable {
    public var phase: String
    public var degradedReason: String?
    public var appVersion: String
    public var hostVersion: String
    public var coreVersion: String
    public var stateSchema: UInt32
    public var processId: UInt32
    public var launchCount: UInt64
    public var startedAtUnixMs: UInt64
    public var updateStatus: String
    public var updateFromVersion: String?
    public var updateTargetVersion: String?
    public var updateFailureReason: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(phase: String, degradedReason: String?, appVersion: String, hostVersion: String, coreVersion: String, stateSchema: UInt32, processId: UInt32, launchCount: UInt64, startedAtUnixMs: UInt64, updateStatus: String, updateFromVersion: String?, updateTargetVersion: String?, updateFailureReason: String?) {
        self.phase = phase
        self.degradedReason = degradedReason
        self.appVersion = appVersion
        self.hostVersion = hostVersion
        self.coreVersion = coreVersion
        self.stateSchema = stateSchema
        self.processId = processId
        self.launchCount = launchCount
        self.startedAtUnixMs = startedAtUnixMs
        self.updateStatus = updateStatus
        self.updateFromVersion = updateFromVersion
        self.updateTargetVersion = updateTargetVersion
        self.updateFailureReason = updateFailureReason
    }




}

#if compiler(>=6)
extension FfiRuntimeHealth: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRuntimeHealth: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRuntimeHealth {
        return
            try FfiRuntimeHealth(
                phase: FfiConverterString.read(from: &buf),
                degradedReason: FfiConverterOptionString.read(from: &buf),
                appVersion: FfiConverterString.read(from: &buf),
                hostVersion: FfiConverterString.read(from: &buf),
                coreVersion: FfiConverterString.read(from: &buf),
                stateSchema: FfiConverterUInt32.read(from: &buf),
                processId: FfiConverterUInt32.read(from: &buf),
                launchCount: FfiConverterUInt64.read(from: &buf),
                startedAtUnixMs: FfiConverterUInt64.read(from: &buf),
                updateStatus: FfiConverterString.read(from: &buf),
                updateFromVersion: FfiConverterOptionString.read(from: &buf),
                updateTargetVersion: FfiConverterOptionString.read(from: &buf),
                updateFailureReason: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRuntimeHealth, into buf: inout [UInt8]) {
        FfiConverterString.write(value.phase, into: &buf)
        FfiConverterOptionString.write(value.degradedReason, into: &buf)
        FfiConverterString.write(value.appVersion, into: &buf)
        FfiConverterString.write(value.hostVersion, into: &buf)
        FfiConverterString.write(value.coreVersion, into: &buf)
        FfiConverterUInt32.write(value.stateSchema, into: &buf)
        FfiConverterUInt32.write(value.processId, into: &buf)
        FfiConverterUInt64.write(value.launchCount, into: &buf)
        FfiConverterUInt64.write(value.startedAtUnixMs, into: &buf)
        FfiConverterString.write(value.updateStatus, into: &buf)
        FfiConverterOptionString.write(value.updateFromVersion, into: &buf)
        FfiConverterOptionString.write(value.updateTargetVersion, into: &buf)
        FfiConverterOptionString.write(value.updateFailureReason, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRuntimeHealth_lift(_ buf: RustBuffer) throws -> FfiRuntimeHealth {
    return try FfiConverterTypeFfiRuntimeHealth.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRuntimeHealth_lower(_ value: FfiRuntimeHealth) -> RustBuffer {
    return FfiConverterTypeFfiRuntimeHealth.lower(value)
}


public
enum CompanionFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Runtime(message: String
    )
    case LockPoisoned






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension CompanionFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCompanionFfiError: FfiConverterRustBuffer {
    typealias SwiftType = CompanionFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CompanionFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Runtime(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .LockPoisoned

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CompanionFfiError, into buf: inout [UInt8]) {
        switch value {





        case let .Runtime(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)


        case .LockPoisoned:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompanionFfiError_lift(_ buf: RustBuffer) throws -> CompanionFfiError {
    return try FfiConverterTypeCompanionFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCompanionFfiError_lower(_ value: CompanionFfiError) -> RustBuffer {
    return FfiConverterTypeCompanionFfiError.lower(value)
}



public enum FfiAppServerAvailability: Equatable, Hashable {

    case available(version: String
    )
    case unavailable





}

#if compiler(>=6)
extension FfiAppServerAvailability: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAppServerAvailability: FfiConverterRustBuffer {
    typealias SwiftType = FfiAppServerAvailability

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAppServerAvailability {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .available(version: try FfiConverterString.read(from: &buf)
        )

        case 2: return .unavailable

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiAppServerAvailability, into buf: inout [UInt8]) {
        switch value {


        case let .available(version):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(version, into: &buf)


        case .unavailable:
            writeInt(&buf, Int32(2))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerAvailability_lift(_ buf: RustBuffer) throws -> FfiAppServerAvailability {
    return try FfiConverterTypeFfiAppServerAvailability.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerAvailability_lower(_ value: FfiAppServerAvailability) -> RustBuffer {
    return FfiConverterTypeFfiAppServerAvailability.lower(value)
}




public enum FfiAppServerConnection: Equatable, Hashable {

    case live(version: String?
    )
    case reconnecting(lastKnownVersion: String?
    )





}

#if compiler(>=6)
extension FfiAppServerConnection: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAppServerConnection: FfiConverterRustBuffer {
    typealias SwiftType = FfiAppServerConnection

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAppServerConnection {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .live(version: try FfiConverterOptionString.read(from: &buf)
        )

        case 2: return .reconnecting(lastKnownVersion: try FfiConverterOptionString.read(from: &buf)
        )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiAppServerConnection, into buf: inout [UInt8]) {
        switch value {


        case let .live(version):
            writeInt(&buf, Int32(1))
            FfiConverterOptionString.write(version, into: &buf)


        case let .reconnecting(lastKnownVersion):
            writeInt(&buf, Int32(2))
            FfiConverterOptionString.write(lastKnownVersion, into: &buf)

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerConnection_lift(_ buf: RustBuffer) throws -> FfiAppServerConnection {
    return try FfiConverterTypeFfiAppServerConnection.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAppServerConnection_lower(_ value: FfiAppServerConnection) -> RustBuffer {
    return FfiConverterTypeFfiAppServerConnection.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiAppServerCandidate: FfiConverterRustBuffer {
    typealias SwiftType = [FfiAppServerCandidate]

    public static func write(_ value: [FfiAppServerCandidate], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiAppServerCandidate.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiAppServerCandidate] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiAppServerCandidate]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiAppServerCandidate.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiDeviceStatus: FfiConverterRustBuffer {
    typealias SwiftType = [FfiDeviceStatus]

    public static func write(_ value: [FfiDeviceStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiDeviceStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiDeviceStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiDeviceStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiDeviceStatus.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_companion_swift_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_app_server_connection() != 62371) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_create_pairing() != 24799) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_devices() != 59987) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_discover_app_servers() != 45098) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_health() != 9536) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_pair_relay() != 64584) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_prepare_for_update() != 40305) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_relay_status() != 54663) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_revoke_device() != 29457) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_method_corehost_set_relay_enabled() != 8464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_companion_swift_ffi_checksum_constructor_corehost_new() != 64369) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCompanionSwiftFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all