import type { LiveTurnPlan } from "../../../rendering/live-turn-plan";
import type { ReactElement, ReactNode } from "react";
import type { TimelineItem } from "./timelineTypes";
import type { Thread } from "@codewide/codex-protocol/v0.147.0/v2";
import type { RefObject } from "react";
import { View } from "react-native";
import type { ThreadHistoryModel } from "../../../data/thread-history-model";
import type { ThreadHistoryViewport } from "../../../data/use-thread-history-controller";
import type { MessageListState } from "../../../ui/MessageListBoundary";
export type ConversationTimelineSurfaceProps = {
  timelineViewportRef: RefObject<View | null>;
  draftConnectionId: string | null;
  draftThreadId: string | null;
  composerScope: string;
  timeline: TimelineItem[];
  readOnly: boolean;
  historyViewport: ThreadHistoryViewport;
  latestUnreadReceiptKey: string | null;
  commitUnreadReceipt: () => () => void;
  messageListState: MessageListState;
  positionSearchTurn: () => void;
  completeLatestJump: () => void;
  timelineModelReady: boolean;
  timelinePositioned: boolean;
  remoteThread: Thread | null | undefined;
  initialRestoreAnchorTurnId: string | null;
  timelineDidLoad: boolean;
  timelineGestureActive: boolean;
  fullscreenCovered: boolean;
  awayFromLatest: boolean;
  threadSearchActive: boolean;
  timelineContent: ReactElement;
  historyActivityModel: ThreadHistoryModel | null;
  historyActivityResourceId: string | null;
  liveStatusVisible: boolean;
  bottomChromeHeight: number;
  liveTurnPlan: LiveTurnPlan | null;
  goalContent: ReactNode;
};
