import { StyleSheet } from "react-native";
import {
  colors,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";
import { threadListLayout } from "../../ui/thread-list-layout";

export const styles = StyleSheet.create({
  workspace: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    flexDirection: "row",
    backgroundColor: colors.threadListSurface,
  },
  master: {
    minWidth: 0,
    minHeight: 0,
    backgroundColor: colors.threadListSurface,
  },
  detail: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    backgroundColor: colors.conversationSurface,
  },
  detailRaised: {
    borderTopLeftRadius: radii.composer,
    borderBottomLeftRadius: radii.composer,
    overflow: "hidden",
  },
  masterHeader: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
    paddingLeft: threadListLayout.edgeInset,
    paddingRight: spacing.md,
  },
  detailHeader: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
  },
  headerIdentity: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    color: colors.text,
    ...typeScale.title,
  },
  masterTitle: {
    flex: 1,
    minWidth: 0,
  },
  headerCount: {
    flexShrink: 0,
    color: colors.textMuted,
    ...typeScale.label,
  },
  headerSubtitle: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  iconButton: {
    width: touchTarget,
    height: touchTarget,
    borderRadius: radii.large,
    alignItems: "center",
    justifyContent: "center",
  },
  listContent: { paddingBottom: spacing.md },
  row: {
    height: threadListLayout.rowContentHeight,
    marginHorizontal: threadListLayout.edgeInset,
    marginVertical: threadListLayout.rowVerticalMargin,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.compact,
    borderRadius: radii.selected,
    flexDirection: "row",
    alignItems: "center",
  },
  rowSelected: { backgroundColor: colors.secondaryContainer },
  pressed: { opacity: 0.68 },
  rowText: {
    flex: 1,
    minWidth: 0,
    gap: spacing.optical,
  },
  rowTitleLine: {
    width: "100%",
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  rowTitle: {
    minWidth: 0,
    flexShrink: 1,
    color: colors.text,
    ...typeScale.body,
    fontWeight: typeWeight.semibold,
  },
  rowTitleWave: { flex: 1 },
  statusIcon: {
    width: 18,
    height: 18,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  rowMeta: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
  },
  unreadSlot: {
    width: 7,
    height: 18,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  unreadDot: {
    width: 7,
    height: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
  },
  time: {
    flexShrink: 0,
    color: colors.textMuted,
    ...typeScale.caption,
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  preview: {
    minWidth: 0,
    maxWidth: "100%",
    flexShrink: 1,
    color: colors.textMuted,
    ...typeScale.label,
  },
  pendingPane: {
    flex: 1,
    minHeight: 0,
  },
  center: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  empty: {
    minHeight: 180,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  muted: {
    color: colors.textMuted,
    ...typeScale.body,
  },
  error: {
    color: colors.red,
    padding: spacing.sm,
    ...typeScale.body,
  },
});
