const metroPlatformEntrypoints = [
  // WHY: Metro selects these files by platform before the unsuffixed fallback that Knip resolves.
  "src/boot/applicationRestart.web.ts",
  "src/boot/uiGenerationStore.web.ts",
  "src/v2/infrastructure/attachments/closedComposerAttachmentTransport.web.ts",
  "src/v2/infrastructure/connection/sharedConnectionAdapter.native.ts",
  "src/v2/infrastructure/connection/sharedConnectionAdapter.web.ts",
  "src/v2/infrastructure/persistence/sqliteCommandCorrelationStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteComposerDraftStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteDocumentViewerPreferenceStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteOperationStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteProjectionStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteSavedServerDeletionStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteSavedServerRepository.web.ts",
  "src/v2/infrastructure/persistence/sqliteTerminalSessionStore.web.ts",
  "src/v2/infrastructure/persistence/sqliteThreadPinStore.web.ts",
  "src/v2/infrastructure/ports/closedPortTransport.web.ts",
  "src/v2/infrastructure/ports/nativeBrowserDevTools.web.ts",
  "src/v2/infrastructure/preview/closedPreviewTransport.web.ts",
  "src/v2/infrastructure/preview/previewFileTransfer.web.ts",
  "src/v2/infrastructure/react/terminal/TerminalRendererView.web.tsx",
  "src/v2/infrastructure/react/useContentReviewSelectionBinding.native.ts",
  "src/v2/infrastructure/terminal/closedTerminalTransport.web.ts",
  "src/v2/infrastructure/terminal/terminalLifecycle.web.ts",
  "src/v2/platform/drawing/quickdrawImageSource.web.ts",
  "src/v2/presentation/diagnostics/SpeedscopeProfileViewer.native.tsx",
  "src/v2/presentation/diagnostics/SpeedscopeProfileViewer.web.tsx",
  "src/v2/presentation/surfaces/PresentationSheetView.android.tsx",
  "src/v2/presentation/usage/CostBreakdownPopover.android.tsx",
  "src/v2/presentation/usage/LiveTurnPlanPopover.android.tsx",
  "src/v2/presentation/usage/UsagePopoverView.android.tsx",
  "src/v2/rendering/Diagram.native.tsx",
  "src/v2/rendering/Diagram.web.tsx",
  "src/v2/rendering/ReviewableText.native.tsx",
  "src/v2/ui/ActionMenu.native.tsx",
  "src/v2/ui/ActionMenu.web.tsx",
  "src/v2/ui/MessageActionMenu.native.tsx",
  "src/v2/ui/MessageActionMenu.web.tsx",
];

export default {
  babel: false,
  "dependency-cruiser": false,
  eslint: false,
  expo: false,
  metro: false,
  typescript: false,
  ignoreUnresolved: [
    "^\\.\\./native/performance-metrics$",
    "^\\.\\./v2/presentation/diagnostics/SpeedscopeProfileViewer$",
    "^\\./Diagram$",
    "^(?:\\.\\./){2,3}ui/(?:ActionMenu|MessageActionMenu)$",
    "^(?:\\.\\./){3}data/connection-profile-database$",
  ],
  // WHY: Exact legacy bridge and test-only seams stay exported for excluded external routes and regressions.
  tags: ["-legacyBridge", "-testOnly"],
  entry: [
    // Expo Router owns every route below these groups; the root V1/V2 bridge stays outside this gate.
    "app/**/*.tsx",
    "!app/_layout.tsx",
    "!app/index.tsx",
    "!app/legacy.tsx",
    "!app/pair.tsx",
    "!app/thread.tsx",
    "src/boot/RootGenerationGate.tsx",
    // WHY: The excluded legacy root bridge dynamically owns this cross-generation diagnostics host.
    "src/boot/UiGenerationDiagnosticsHost.tsx",
    "src/v2/V2Application.tsx",
    ...metroPlatformEntrypoints,
  ],
  project: [
    "app/**/*.{ts,tsx}",
    "src/boot/**/*.{ts,tsx}",
    "src/v2/**/*.{ts,tsx}",
    "!app/_layout.tsx",
    "!app/index.tsx",
    "!app/legacy.tsx",
    "!app/pair.tsx",
    "!app/thread.tsx",
  ],
};
