#!/bin/sh
set -eu

# Product-only releases and unfinished drafts are not complete inventory bases.
gh release list --limit 1000 --json tagName,isDraft,isPrerelease \
  --jq '[.[] | select(.isDraft == false and .isPrerelease == false) | .tagName | select(test("^(v[0-9]+[.][0-9]+[.][0-9]+|release-[0-9]{4}-[0-9]{2}-[0-9]{2}[.][1-9][0-9]*)$"))] | first // ""'
