import { StyleSheet } from "react-native";

import { colors, radii, spacing, touchTarget, typeScale, typeTracking } from "../../theme";

export const projectPickerStyles = StyleSheet.create({
  close: {
    alignItems: "center",
    borderRadius: radii.large,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  content: { paddingBottom: spacing.lg },
  empty: { alignItems: "center", gap: spacing.xs, paddingVertical: spacing.xl },
  error: { paddingHorizontal: spacing.xs, paddingVertical: spacing.xs },
  header: { alignItems: "center", flexDirection: "row", minHeight: 56 },
  headerCopy: { flex: 1, minWidth: 0 },
  list: { flex: 1, minHeight: 0 },
  pendingText: { color: colors.accent, ...typeScale.caption },
  pin: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: touchTarget,
    minWidth: touchTarget,
  },
  pinText: { color: colors.textMuted, ...typeScale.caption },
  pressed: { opacity: 0.68 },
  row: {
    alignItems: "center",
    borderRadius: radii.selected,
    flexDirection: "row",
    minHeight: 64,
  },
  rowContent: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 64,
    minWidth: 0,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  rowCopy: { flex: 1, minWidth: 0 },
  rowDetail: { ...typeScale.label, marginTop: spacing.optical },
  rowIcon: {
    alignItems: "center",
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.large,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  rowSelected: { backgroundColor: colors.secondaryContainer },
  rowTitle: { ...typeScale.body },
  search: {
    alignItems: "center",
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.large,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
  },
  searchInput: {
    color: colors.text,
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    ...typeScale.body,
  },
  section: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
    paddingBottom: spacing.xxs,
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.sm,
  },
  sectionCount: { ...typeScale.caption },
  sectionTitle: {
    ...typeScale.caption,
    letterSpacing: typeTracking.caps,
    textTransform: "uppercase",
  },
  subtitle: { ...typeScale.label },
  title: { ...typeScale.heading },
});
