import { Platform, StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeTracking,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  menuNotice: { color: colors.textMuted, ...typeScale.body, paddingVertical: spacing.xs },
  menuActionSubtitle: { color: colors.textMuted, ...typeScale.label, marginTop: spacing.optical },
  disabled: { opacity: 0.42 },
  fieldLabel: { color: colors.textMuted, ...typeScale.label, marginTop: spacing.xxs },
  errorText: { color: colors.red, ...typeScale.body },
  secondaryButton: {
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  secondaryButtonText: { color: colors.text, fontWeight: typeWeight.semibold },
  primaryButton: {
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
    backgroundColor: colors.primary,
  },
  primaryButtonText: { color: colors.onPrimary, fontWeight: typeWeight.semibold },
  connectionMiniButton: {
    width: touchTarget,
    height: touchTarget,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
  },
  connectionStateDot: { width: 7, height: 7, borderRadius: radii.pill },
  accountPoolEditor: { gap: 0, marginTop: spacing.md },
  accountPoolHeader: {
    minHeight: controlSize.touch,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  accountPoolLimit: {
    flexShrink: 0,
    color: colors.text,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
    fontVariant: ["tabular-nums"],
  },
  accountPoolLimitPending: { color: colors.textDim, fontWeight: typeWeight.semibold },
  accountPoolMenuAnchor: { width: touchTarget, height: touchTarget, flexShrink: 0 },
  accountPoolAddButton: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  accountLoginSheet: { gap: spacing.md, paddingBottom: spacing.xs },
  accountLoginHeader: {
    minHeight: touchTarget,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  accountLoginIcon: {
    width: controlSize.regular,
    height: controlSize.regular,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.large,
    backgroundColor: colors.primaryContainer,
  },
  accountLoginTitle: { color: colors.text, ...typeScale.heading },
  accountLoginSubtitle: { color: colors.textMuted, ...typeScale.body, marginTop: spacing.optical },
  accountLoginCodeCard: {
    minHeight: 92,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    padding: spacing.md,
    borderRadius: radii.large,
    backgroundColor: colors.surfaceContainerLow,
  },
  accountLoginCodeLabel: { color: colors.textMuted, ...typeScale.label },
  accountLoginCode: {
    color: colors.text,
    ...typeScale.heading,
    fontFamily: Platform.select({ android: "monospace", default: "Courier" }),
    letterSpacing: typeTracking.pairingCode,
  },
  accountLoginCopyButton: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xxs,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.medium,
    borderWidth: 1,
    borderColor: colors.outline,
  },
  accountLoginCopyButtonDone: {
    borderColor: colors.green,
    backgroundColor: colors.successContainer,
  },
  accountLoginCopyLabel: {
    color: colors.text,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  accountLoginCopyLabelDone: { color: colors.green },
  accountLoginHint: { color: colors.textMuted, ...typeScale.body },
  accountLoginPrimaryButton: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    gap: spacing.xs,
  },
});
