import { StyleSheet } from "react-native";

import {
  colors,
  controlSize,
  layoutSize,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  content: { paddingVertical: spacing.xxs },
  section: { gap: spacing.xs, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  dividedSection: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  sessionSummaryRow: {
    minHeight: controlSize.regular,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  sessionSummaryValues: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: spacing.xxs,
  },
  sessionSummaryText: {
    flexShrink: 1,
    minWidth: 0,
    textAlign: "right",
    color: colors.textMuted,
    ...typeScale.label,
    fontVariant: ["tabular-nums"],
  },
  sessionSummarySeparator: { flexShrink: 0, color: colors.textMuted, ...typeScale.label },
  sessionCostText: {
    flexShrink: 0,
    color: colors.textMuted,
    ...typeScale.label,
    fontVariant: ["tabular-nums"],
  },
  contextSummary: {
    minHeight: layoutSize.header,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
  },
  contextRingLabel: {
    position: "absolute",
    inset: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  contextRingNumber: { width: "100%", alignItems: "center" },
  contextRingLabelText: {
    width: "100%",
    color: colors.text,
    fontWeight: typeWeight.semibold,
    textAlign: "center",
    includeFontPadding: false,
  },
  grow: { flex: 1, minWidth: 0 },
  title: { color: colors.textMuted, ...typeScale.label },
  primaryValue: {
    color: colors.text,
    ...typeScale.heading,
    fontWeight: typeWeight.semibold,
    fontVariant: ["tabular-nums"],
  },
  secondaryValue: { color: colors.textMuted, ...typeScale.body, fontVariant: ["tabular-nums"] },
  meta: { color: colors.textDim, ...typeScale.label },
  unavailable: { color: colors.textMuted },
  weeklyHeader: {
    minHeight: controlSize.compact,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
  },
  weeklyTitle: { flexDirection: "row", alignItems: "center", gap: spacing.xs },
  weeklyValue: {
    flexShrink: 1,
    color: colors.text,
    ...typeScale.title,
    fontWeight: typeWeight.semibold,
    fontVariant: ["tabular-nums"],
  },
  accountValue: {
    flexShrink: 0,
    color: colors.text,
    ...typeScale.body,
    fontVariant: ["tabular-nums"],
  },
  resetRow: {
    minHeight: layoutSize.metadataRow,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  action: {
    minHeight: touchTarget,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  dividedAction: { borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.border },
  actionIcon: {
    width: 20,
    height: 20,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  actionTitle: { color: colors.text, ...typeScale.body },
  error: { color: colors.red, ...typeScale.label },
  disabled: { opacity: 0.4 },
  pressed: { opacity: 0.7 },
});
