import type { Dispatch, SetStateAction } from "react";
import type { NativeScrollEvent, NativeSyntheticEvent, useWindowDimensions } from "react-native";
import type { AsyncResourceSnapshot } from "../../rendering/async-resource-store";
import type { SearchScreenProps } from "./globalSearchContract";
import type { SearchRequest, SearchSession } from "./search-session";
import type { SearchDateField, SearchFilterValue } from "./SearchFilters";
import type { SearchResultTarget, ServerSearchResult } from "./searchResultTypes";

export type renderGlobalSearchViewInput = {
  autoFocus: boolean;
  calendar: SearchDateField | null;
  clear: () => void;
  close: () => void;
  didFocus: () => void;
  dismissCalendar: () => void;
  failed: boolean;
  filterCount: number;
  filterError: string | null;
  filters: boolean;
  filterValue: SearchFilterValue;
  nextPage: () => void;
  pickDate: (field: SearchDateField) => void;
  previousPage: () => void;
  props: SearchScreenProps;
  request: SearchRequest | null;
  resetFilters: () => void;
  resource: AsyncResourceSnapshot<readonly ServerSearchResult[]>;
  results: SearchResultTarget[];
  saveOffset: (event: NativeSyntheticEvent<NativeScrollEvent>) => void;
  search: () => void;
  selectCalendarDay: (day: string) => void;
  selectResult: (target: SearchResultTarget) => void;
  session: SearchSession;
  setFilters: Dispatch<SetStateAction<boolean>>;
  setFilterValue: (value: SearchFilterValue) => void;
  setText: (value: string) => void;
  text: string;
  toggleFilters: () => void;
  window: ReturnType<typeof useWindowDimensions>;
};
