import { ConversationEmptyState } from "./ConversationEmptyState";
import { ConversationQueueFooter } from "./ConversationQueueFooter";
import type { CreateConversationTimelineContentProps } from "./ConversationTimelineContent.types";
import { ConversationTimelineSurface } from "./timeline/ConversationTimelineSurface";
import { TimelineViewport } from "./timeline/TimelineViewport";
export function createConversationTimelineContent(props: CreateConversationTimelineContentProps) {
  const timelineContent = (
    <TimelineViewport
      composerScope={props.composerScope}
      timelineRef={props.timelineState.timelineViewportStateBinding.timelineRef}
      displayedTimeline={props.timelineRead.timelineSearchProjectionBinding.displayedTimeline}
      timelineInitialPosition={props.timelineRead.timelineInitialPosition}
      threadSearch={props.timelineState.timelineSearchStateBinding.threadSearch}
      threadSearchMatch={props.timelineState.timelineSearchStateBinding.threadSearchMatch}
      windowLayout={props.windowLayout}
      timelineCompact={props.timelineCompact}
      bottomChromeHeight={props.timelineState.timelineViewportStateBinding.bottomChromeHeight}
      liveStatusVisible={props.liveStatusVisible}
      threadSearchVisible={props.timelineState.timelineSearchStateBinding.threadSearchVisible}
      conversationInsets={props.conversationInsets}
      fullscreenCovered={props.overlayScrollStateBinding.fullscreenCovered}
      historyViewport={props.historyViewport}
      awayFromLatest={props.timelineState.historyAnchorStateBinding.awayFromLatest}
      threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
      inlineQueueExpanded={props.queueVisibilityBinding.inlineQueueExpanded}
      draftConnectionId={props.draftConnectionId}
      draftThreadId={props.draftThreadId}
      commitInitialTimelineLoad={
        props.timelineRead.historyAnchorActionsBinding.commitInitialTimelineLoad
      }
      timelineViewportHeightRef={
        props.timelineState.timelineViewportStateBinding.timelineViewportHeightRef
      }
      reportHistoryViewport={
        props.timelineRead.timelineViewportActionsBinding.reportHistoryViewport
      }
      scheduleUnreadAgentVisibilityCheck={
        props.timelineRead.unreadReceiptActionsBinding.scheduleUnreadAgentVisibilityCheck
      }
      setTimelineGestureActive={
        props.timelineState.timelineViewportStateBinding.setTimelineGestureActive
      }
      fullscreenScrollOwnership={props.overlayScrollStateBinding.fullscreenScrollOwnership}
      cancelScheduledPaginationTrim={props.paginationTrimBinding.cancelScheduledPaginationTrim}
      paginationEdgeLockRef={props.timelineState.timelineViewportStateBinding.paginationEdgeLockRef}
      scrollGestureStartedAtRef={
        props.timelineState.timelineViewportStateBinding.scrollGestureStartedAtRef
      }
      lastTimelineOffsetYRef={
        props.timelineState.timelineViewportStateBinding.lastTimelineOffsetYRef
      }
      firstVisibleHistoryAnchorRef={
        props.timelineState.historyAnchorStateBinding.firstVisibleHistoryAnchorRef
      }
      timelineContentHeightRef={
        props.timelineState.timelineViewportStateBinding.timelineContentHeightRef
      }
      scrollOffsetRef={props.timelineState.timelineViewportStateBinding.scrollOffsetRef}
      awayFromLatestRef={props.timelineState.historyAnchorStateBinding.awayFromLatestRef}
      setAwayFromLatest={props.timelineState.historyAnchorStateBinding.setAwayFromLatest}
      persistTimelineAtEnd={props.timelineRead.historyAnchorActionsBinding.persistTimelineAtEnd}
      schedulePaginationWindowTrim={props.paginationTrimBinding.schedulePaginationWindowTrim}
      persistTimelineOffset={props.timelineRead.historyAnchorActionsBinding.persistTimelineOffset}
      trimPaginationWindow={props.paginationTrimBinding.trimPaginationWindow}
      timelinePositioned={props.timelineRead.timelinePositioned}
      loadOlderAtTimelineStart={
        props.timelineRead.timelineViewportActionsBinding.loadOlderAtTimelineStart
      }
      loadNewerAtTimelineEnd={
        props.timelineRead.timelineViewportActionsBinding.loadNewerAtTimelineEnd
      }
      onTimelineFirstVisibleItemChanged={
        props.timelineRead.timelineViewportActionsBinding.onTimelineFirstVisibleItemChanged
      }
      renderTimelineItem={props.threadTimelineBinding.renderTimelineItem}
      emptyContent={
        <ConversationEmptyState
          threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
          emptyRemoteThread={props.timelineRead.emptyRemoteThread}
          cwd={props.cwd}
          openProjectPicker={props.composerProjectSelectionBinding.openProjectPicker}
          workspaceSupport={props.workspaceSupport}
          onChangeWorkspaceMode={props.projectsInputs.onChangeWorkspaceMode}
          workspaceMode={props.workspaceMode}
          historyActivityModel={props.historyActivityModel}
          historyActivityResourceId={props.historyActivityResourceId}
        />
      }
      footerContent={
        <ConversationQueueFooter
          threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
          inlineQueueExpanded={props.queueVisibilityBinding.inlineQueueExpanded}
          queuedPromptEditing={
            props.composerStateBinding.queueEditStateBinding.queuedComposerEdit !== null
          }
          inlineQueueOverlayItems={props.inlineQueueBinding.inlineQueueOverlayItems}
          inlineQueueMaxHeight={props.inlineQueueMaxHeight}
          currentTurnId={props.timelineRead.conversationPresentationBinding.currentTurnId}
          toggleInlineQueueOverlay={props.queueVisibilityBinding.toggleInlineQueueOverlay}
          closeInlineQueueOverlay={props.queueVisibilityBinding.closeInlineQueueOverlay}
          onEditQueued={props.queueInputs.onEditQueued}
          voicePhase={props.composerStateBinding.composerVoiceStateBinding.voicePhase}
          visibleQueuedPrompts={props.visibleQueuedPrompts}
          beginQueuedComposerEdit={props.queueEditActionsBinding.beginQueuedComposerEdit}
          onCancelQueued={props.queueInputs.onCancelQueued}
          onMoveQueued={props.queueInputs.onMoveQueued}
          onRetryFailedMessage={props.composerInputs.onRetryFailedMessage}
          onSteerQueued={props.queueInputs.onSteerQueued}
          onListQueue={props.queueInputs.onListQueue}
        />
      }
    />
  );
  const timelineSurface = (
    <ConversationTimelineSurface
      timelineViewportRef={props.timelineState.timelineViewportStateBinding.timelineViewportRef}
      draftConnectionId={props.draftConnectionId}
      draftThreadId={props.draftThreadId}
      composerScope={props.composerScope}
      timeline={props.timelineRead.conversationTimelineBinding.timeline}
      readOnly={props.readOnly}
      historyViewport={props.historyViewport}
      latestUnreadReceiptKey={props.timelineRead.unreadReceiptBinding.latestUnreadReceiptKey}
      commitUnreadReceipt={props.timelineRead.unreadReceiptActionsBinding.commitUnreadReceipt}
      messageListState={props.messageListState}
      positionSearchTurn={props.timelineRead.timelineSearchActionsBinding.positionSearchTurn}
      completeLatestJump={props.timelineRead.historyAnchorActionsBinding.completeLatestJump}
      timelineModelReady={props.timelineRead.timelineModelReady}
      timelinePositioned={props.timelineRead.timelinePositioned}
      remoteThread={props.readInputs.remoteThread}
      initialRestoreAnchorTurnId={
        props.timelineState.historyAnchorStateBinding.initialRestoreAnchorTurnId
      }
      timelineDidLoad={props.timelineState.timelineViewportStateBinding.timelineDidLoad}
      timelineGestureActive={props.timelineState.timelineViewportStateBinding.timelineGestureActive}
      fullscreenCovered={props.overlayScrollStateBinding.fullscreenCovered}
      awayFromLatest={props.timelineState.historyAnchorStateBinding.awayFromLatest}
      threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
      timelineContent={timelineContent}
      historyActivityModel={props.historyActivityModel}
      historyActivityResourceId={props.historyActivityResourceId}
      liveStatusVisible={props.liveStatusVisible}
      bottomChromeHeight={props.timelineState.timelineViewportStateBinding.bottomChromeHeight}
      liveTurnPlan={props.timelineRead.conversationPresentationBinding.liveTurnPlan}
      goalContent={props.goalContent}
    />
  );
  return { timelineSurface };
}
