import { ConversationEmptyState } from "./ConversationEmptyState";
import { ConversationQueueFooter } from "./ConversationQueueFooter";
import type { CreateConversationTimelineContentProps } from "./ConversationTimelineContent.types";
import { ConversationTimelineSurface } from "./timeline/ConversationTimelineSurface";
import { TimelineViewport } from "./timeline/TimelineViewport";

export function createConversationTimelineContent(props: CreateConversationTimelineContentProps) {
  const timelineContent = (
    <TimelineViewport
      awayFromLatest={props.timelineState.historyAnchorStateBinding.awayFromLatest}
      awayFromLatestRef={props.timelineState.historyAnchorStateBinding.awayFromLatestRef}
      bottomChromeHeight={props.timelineState.timelineViewportStateBinding.bottomChromeHeight}
      cancelScheduledPaginationTrim={props.paginationTrimBinding.cancelScheduledPaginationTrim}
      commitInitialTimelineLoad={
        props.timelineRead.historyAnchorActionsBinding.commitInitialTimelineLoad
      }
      completeTimelineJump={props.timelineRead.timelineJumpActionsBinding.completeTimelineJump}
      composerScope={props.composerScope}
      conversationInsets={props.conversationInsets}
      displayedTimeline={props.timelineRead.timelineSearchProjectionBinding.displayedTimeline}
      draftConnectionId={props.draftConnectionId}
      draftThreadId={props.draftThreadId}
      emptyContent={
        <ConversationEmptyState
          cwd={props.cwd}
          historyActivityModel={props.historyActivityModel}
          historyActivityResourceId={props.historyActivityResourceId}
          newChat={props.timelineRead.newChat}
          onChangeWorkspaceMode={props.projectsInputs.onChangeWorkspaceMode}
          openProjectPicker={props.composerProjectSelectionBinding.openProjectPicker}
          threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
          workspaceMode={props.workspaceMode}
          workspaceSupport={props.workspaceSupport}
        />
      }
      firstVisibleHistoryAnchorRef={
        props.timelineState.historyAnchorStateBinding.firstVisibleHistoryAnchorRef
      }
      footerContent={
        <ConversationQueueFooter
          beginQueuedComposerEdit={props.queueEditActionsBinding.beginQueuedComposerEdit}
          closeInlineQueueOverlay={props.queueVisibilityBinding.closeInlineQueueOverlay}
          currentTurnId={props.timelineRead.conversationPresentationBinding.currentTurnId}
          inlineQueueExpanded={props.queueVisibilityBinding.inlineQueueExpanded}
          inlineQueueMaxHeight={props.inlineQueueMaxHeight}
          inlineQueueOverlayItems={props.inlineQueueBinding.inlineQueueOverlayItems}
          onCancelQueued={props.queueInputs.onCancelQueued}
          onEditQueued={props.queueInputs.onEditQueued}
          onListQueue={props.queueInputs.onListQueue}
          onMoveQueued={props.queueInputs.onMoveQueued}
          onRetryFailedMessage={props.composerInputs.onRetryFailedMessage}
          onSteerQueued={props.queueInputs.onSteerQueued}
          queuedPromptEditing={
            props.composerStateBinding.queueEditStateBinding.queuedComposerEdit !== null
          }
          threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
          toggleInlineQueueOverlay={props.queueVisibilityBinding.toggleInlineQueueOverlay}
          visibleQueuedPrompts={props.visibleQueuedPrompts}
          voicePhase={props.composerStateBinding.composerVoiceStateBinding.voicePhase}
        />
      }
      fullscreenCovered={props.overlayScrollStateBinding.fullscreenCovered}
      fullscreenScrollOwnership={props.overlayScrollStateBinding.fullscreenScrollOwnership}
      historyViewport={props.historyViewport}
      inlineQueueExpanded={props.queueVisibilityBinding.inlineQueueExpanded}
      jumpVisibility={props.timelineState.timelineViewportStateBinding.jumpVisibility}
      lastTimelineOffsetYRef={
        props.timelineState.timelineViewportStateBinding.lastTimelineOffsetYRef
      }
      latestUnreadAgentRef={props.timelineState.unreadReceiptStateBinding.latestUnreadAgentRef}
      latestUnreadAgentTurnId={props.timelineRead.unreadReceiptBinding.latestUnreadAgentTurnId}
      liveStatusVisible={props.liveStatusVisible}
      loadNewerAtTimelineEnd={
        props.timelineRead.timelineViewportActionsBinding.loadNewerAtTimelineEnd
      }
      loadOlderAtTimelineStart={
        props.timelineRead.timelineViewportActionsBinding.loadOlderAtTimelineStart
      }
      newChat={props.timelineRead.newChat}
      onTimelineFirstVisibleItemChanged={
        props.timelineRead.timelineViewportActionsBinding.onTimelineFirstVisibleItemChanged
      }
      paginationEdgeLockRef={props.timelineState.timelineViewportStateBinding.paginationEdgeLockRef}
      persistTimelineAtEnd={props.timelineRead.historyAnchorActionsBinding.persistTimelineAtEnd}
      persistTimelineOffset={props.timelineRead.historyAnchorActionsBinding.persistTimelineOffset}
      renderTimelineItem={props.threadTimelineBinding.renderTimelineItem}
      reportHistoryViewport={
        props.timelineRead.timelineViewportActionsBinding.reportHistoryViewport
      }
      schedulePaginationWindowTrim={props.paginationTrimBinding.schedulePaginationWindowTrim}
      scheduleUnreadAgentVisibilityCheck={
        props.timelineRead.unreadReceiptActionsBinding.scheduleUnreadAgentVisibilityCheck
      }
      scrollGestureStartedAtRef={
        props.timelineState.timelineViewportStateBinding.scrollGestureStartedAtRef
      }
      scrollOffsetRef={props.timelineState.timelineViewportStateBinding.scrollOffsetRef}
      searchMessageItemId={props.timelineRead.searchMessageItemId}
      setAwayFromLatest={props.timelineState.historyAnchorStateBinding.setAwayFromLatest}
      setTimelineGestureActive={
        props.timelineState.timelineViewportStateBinding.setTimelineGestureActive
      }
      threadSearch={props.timelineState.timelineSearchStateBinding.threadSearch}
      threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
      threadSearchMatch={props.timelineState.timelineSearchStateBinding.threadSearchMatch}
      threadSearchVisible={props.timelineState.timelineSearchStateBinding.threadSearchVisible}
      timelineCompact={props.timelineCompact}
      timelineContentHeightRef={
        props.timelineState.timelineViewportStateBinding.timelineContentHeightRef
      }
      timelineJumpRequest={props.timelineRead.timelineJumpActionsBinding.timelineJumpRequest}
      timelinePositioned={props.timelineRead.timelinePositioned}
      timelineRef={props.timelineState.timelineViewportStateBinding.timelineRef}
      timelineViewportHeightRef={
        props.timelineState.timelineViewportStateBinding.timelineViewportHeightRef
      }
      timelineViewportRef={props.timelineState.timelineViewportStateBinding.timelineViewportRef}
      trimPaginationWindow={props.paginationTrimBinding.trimPaginationWindow}
      windowLayout={props.windowLayout}
    />
  );
  const timelineSurface = (
    <ConversationTimelineSurface
      awayFromLatest={props.timelineState.historyAnchorStateBinding.awayFromLatest}
      bottomChromeHeight={props.timelineState.timelineViewportStateBinding.bottomChromeHeight}
      commitUnreadReceipt={props.timelineRead.unreadReceiptActionsBinding.commitUnreadReceipt}
      composerScope={props.composerScope}
      draftConnectionId={props.draftConnectionId}
      draftThreadId={props.draftThreadId}
      fullscreenCovered={props.overlayScrollStateBinding.fullscreenCovered}
      goalContent={props.goalContent}
      historyActivityModel={props.historyActivityModel}
      historyActivityResourceId={props.historyActivityResourceId}
      historyViewport={props.historyViewport}
      latestUnreadReceiptKey={props.timelineRead.unreadReceiptBinding.latestUnreadReceiptKey}
      liveStatusVisible={props.liveStatusVisible}
      liveTurnPlan={props.timelineRead.conversationPresentationBinding.liveTurnPlan}
      messageListState={props.messageListState}
      positionSearchTurn={props.timelineRead.timelineSearchActionsBinding.positionSearchTurn}
      readOnly={props.readOnly}
      remoteThread={props.readInputs.remoteThread}
      threadSearchActive={props.timelineRead.timelineSearchProjectionBinding.threadSearchActive}
      timeline={props.timelineRead.conversationTimelineBinding.timeline}
      timelineContent={timelineContent}
      timelineDidLoad={props.timelineState.timelineViewportStateBinding.timelineDidLoad}
      timelineGestureActive={props.timelineState.timelineViewportStateBinding.timelineGestureActive}
      timelineModelReady={props.timelineRead.timelineModelReady}
      timelinePositioned={props.timelineRead.timelinePositioned}
      timelineViewportRef={props.timelineState.timelineViewportStateBinding.timelineViewportRef}
    />
  );
  return { timelineSurface };
}
