import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeWeight,
} from "../../theme";

export const styles = StyleSheet.create({
  composerContextText: {
    color: colors.textMuted,
    flexGrow: 0,
    flexShrink: 0,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  conversationSubtitle: {
    color: colors.textMuted,
    ...typeScale.label,
    marginTop: spacing.optical,
  },
  conversationTitle: {
    color: colors.text,
    ...typeScale.title,
  },
  errorText: {
    color: colors.red,
    ...typeScale.body,
  },
  fieldInput: {
    backgroundColor: colors.surfaceContainerLow,
    borderColor: colors.outline,
    borderRadius: radii.medium,
    borderWidth: 1,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
    ...typeScale.body,
  },
  fieldLabel: {
    color: colors.textMuted,
    ...typeScale.label,
    marginTop: spacing.xxs,
  },
  headerIcon: {
    alignItems: "center",
    borderRadius: radii.large,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  livePill: {
    backgroundColor: colors.successContainer,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.inputInset,
    paddingVertical: spacing.xxs,
  },
  livePillText: {
    color: colors.green,
    ...typeScale.label,
    fontWeight: typeWeight.semibold,
  },
  menuNotice: {
    color: colors.textMuted,
    ...typeScale.body,
    paddingVertical: spacing.xs,
  },
  previewEmbeddedRoot: {
    borderRadius: radii.medium,
    minHeight: 0,
    overflow: "hidden",
    width: "100%",
  },
  previewHeader: {
    alignItems: "center",
    backgroundColor: colors.surface,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.inputInset,
    minHeight: layoutSize.header,
    paddingHorizontal: spacing.inputInset,
  },
  previewIdentity: {
    flex: 1,
    minWidth: 0,
  },
  previewRoot: {
    backgroundColor: colors.background,
    flex: 1,
  },
  previewSetup: {
    alignSelf: "center",
    gap: spacing.inputInset,
    maxWidth: 520,
    padding: spacing.lg,
    width: "100%",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.medium,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontWeight: typeWeight.semibold,
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: colors.outline,
    borderRadius: radii.medium,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.md,
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: typeWeight.semibold,
  },
  sheetTitle: {
    color: colors.text,
    flexShrink: 1,
    minWidth: 0,
    ...typeScale.heading,
  },
  tunnelTtlChip: {
    alignItems: "center",
    backgroundColor: colors.surfaceContainer,
    borderRadius: radii.medium,
    justifyContent: "center",
    minHeight: controlSize.compact,
    paddingHorizontal: spacing.sm,
  },
  tunnelTtlChipSelected: { backgroundColor: colors.primaryContainer },
  tunnelTtlChoices: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.compact,
  },
});
