import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeTracking,
  typeWeight,
} from "../../theme";
import { GROUP_HEIGHT, PROFILE_ERROR_HEIGHT } from "./portForwardingList";

export const styles = StyleSheet.create({
  divider: {
    backgroundColor: colors.borderSoft,
    height: StyleSheet.hairlineWidth,
    marginLeft: spacing.sm,
  },
  errorText: {
    color: colors.red,
    flex: 1,
    ...typeScale.label,
  },
  fieldLabel: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  filters: {
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  formActions: {
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "flex-end",
    marginTop: spacing.sm,
    minHeight: touchTarget,
  },
  formContent: {
    gap: spacing.xs,
    padding: spacing.sm,
  },
  formGroup: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.selected,
    marginTop: spacing.xs,
    overflow: "hidden",
  },
  groupCell: { height: GROUP_HEIGHT },
  header: {
    alignItems: "center",
    flexDirection: "row",
    marginBottom: spacing.xs,
    minHeight: touchTarget,
  },
  iconButton: {
    alignItems: "center",
    borderRadius: radii.large,
    height: touchTarget,
    justifyContent: "center",
    width: touchTarget,
  },
  inlineError: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
  },
  list: {
    flex: 1,
    minHeight: 0,
  },
  listContent: { paddingBottom: spacing.md },
  liveDot: {
    backgroundColor: colors.green,
    borderColor: colors.surface,
    borderRadius: radii.pill,
    borderWidth: 2,
    bottom: 1,
    height: 9,
    position: "absolute",
    right: 0,
    width: 9,
  },
  portField: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: layoutSize.row,
    paddingHorizontal: spacing.sm,
  },
  portInput: {
    color: colors.text,
    fontVariant: ["tabular-nums"],
    minHeight: touchTarget,
    paddingVertical: spacing.xs,
    textAlign: "right",
    width: 82,
  },
  pressed: { opacity: 0.64 },
  primaryButton: {
    alignItems: "center",
    backgroundColor: colors.primary,
    borderRadius: radii.large,
    justifyContent: "center",
    minHeight: touchTarget,
    minWidth: controlSize.touch,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  primaryText: {
    color: colors.onPrimary,
    ...typeScale.body,
  },
  profileError: {
    color: colors.red,
    marginBottom: spacing.xxs,
    marginLeft: controlSize.regular + spacing.sm,
    marginRight: spacing.md,
    ...typeScale.label,
  },
  profileErrorCell: { height: PROFILE_ERROR_HEIGHT },
  profileUnavailable: { color: colors.amber },
  removeButton: {
    justifyContent: "center",
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  removeText: {
    color: colors.red,
    ...typeScale.body,
  },
  root: {
    flex: 1,
    minHeight: 0,
    width: "100%",
  },
  rowPressed: { backgroundColor: colors.surfaceHover },
  rowSubtitle: {
    color: colors.textMuted,
    ...typeScale.label,
    fontVariant: ["tabular-nums"],
  },
  rowText: {
    flex: 1,
    gap: spacing.optical,
    minWidth: 0,
  },
  rowTitle: {
    color: colors.text,
    flexShrink: 1,
    ...typeScale.body,
    fontWeight: typeWeight.medium,
  },
  searchField: {
    alignItems: "center",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.selected,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: controlSize.touch,
    paddingHorizontal: spacing.sm,
  },
  searchInput: {
    color: colors.text,
    flex: 1,
    minHeight: controlSize.touch,
    minWidth: 0,
    paddingVertical: 0,
    ...typeScale.body,
  },
  sectionLabel: {
    color: colors.textDim,
    marginBottom: spacing.xxs,
    marginTop: spacing.sm,
    ...typeScale.caption,
    fontWeight: typeWeight.semibold,
    letterSpacing: typeTracking.caps,
  },
  segment: {
    alignItems: "center",
    borderRadius: radii.medium,
    flex: 1,
    justifyContent: "center",
    minHeight: controlSize.compact,
  },
  segments: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.selected,
    flexDirection: "row",
    minHeight: controlSize.compact,
    padding: spacing.optical,
  },
  segmentSelected: { backgroundColor: colors.surfaceHover },
  segmentText: {
    color: colors.textMuted,
    ...typeScale.label,
    fontWeight: typeWeight.medium,
  },
  segmentTextSelected: { color: colors.text },
  serviceIcon: {
    alignItems: "center",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.pill,
    flexShrink: 0,
    height: controlSize.regular,
    justifyContent: "center",
    position: "relative",
    width: controlSize.regular,
  },
  smallAction: {
    justifyContent: "center",
    minHeight: controlSize.regular,
    paddingHorizontal: spacing.sm,
  },
  smallActionText: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  subtitle: {
    color: colors.textMuted,
    ...typeScale.label,
  },
  switchRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: layoutSize.row,
    paddingHorizontal: spacing.sm,
  },
  textInput: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: radii.selected,
    color: colors.text,
    minHeight: touchTarget,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  title: {
    color: colors.text,
    ...typeScale.heading,
    fontWeight: typeWeight.semibold,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
  },
  webActions: {
    flexDirection: "row",
    height: controlSize.regular,
    justifyContent: "flex-end",
    paddingHorizontal: spacing.sm,
  },
});
