import { StyleSheet } from "react-native";
import {
  colors,
  controlSize,
  layoutSize,
  radii,
  spacing,
  touchTarget,
  typeScale,
  typeTracking,
  typeWeight,
} from "../../theme";
import { GROUP_HEIGHT, PROFILE_ERROR_HEIGHT } from "./portForwardingList";
export const styles = StyleSheet.create({
  root: { flex: 1, minHeight: 0, width: "100%" },
  header: {
    minHeight: touchTarget,
    marginBottom: spacing.xs,
    flexDirection: "row",
    alignItems: "center",
  },
  titleBlock: { flex: 1, minWidth: 0 },
  title: { color: colors.text, ...typeScale.heading, fontWeight: typeWeight.semibold },
  subtitle: { color: colors.textMuted, ...typeScale.label },
  iconButton: {
    width: touchTarget,
    height: touchTarget,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.large,
  },
  filters: { gap: spacing.xs, paddingBottom: spacing.xs },
  segments: {
    minHeight: controlSize.compact,
    flexDirection: "row",
    padding: spacing.optical,
    borderRadius: radii.selected,
    backgroundColor: colors.surfaceContainerLow,
  },
  segment: {
    flex: 1,
    minHeight: controlSize.compact,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.medium,
  },
  segmentSelected: { backgroundColor: colors.surfaceHover },
  segmentText: { color: colors.textMuted, ...typeScale.label, fontWeight: typeWeight.medium },
  segmentTextSelected: { color: colors.text },
  searchField: {
    minHeight: controlSize.touch,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.selected,
    backgroundColor: colors.surfaceContainerLow,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    minHeight: controlSize.touch,
    paddingVertical: 0,
    color: colors.text,
    ...typeScale.body,
  },
  listContent: { paddingBottom: spacing.md },
  list: { flex: 1, minHeight: 0 },
  groupCell: { height: GROUP_HEIGHT },
  profileErrorCell: { height: PROFILE_ERROR_HEIGHT },
  sectionLabel: {
    marginTop: spacing.sm,
    marginBottom: spacing.xxs,
    color: colors.textDim,
    ...typeScale.caption,
    letterSpacing: typeTracking.caps,
    fontWeight: typeWeight.semibold,
  },
  serviceIcon: {
    width: controlSize.regular,
    height: controlSize.regular,
    flexShrink: 0,
    borderRadius: radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceContainerLow,
    position: "relative",
  },
  liveDot: {
    position: "absolute",
    right: 0,
    bottom: 1,
    width: 9,
    height: 9,
    borderRadius: radii.pill,
    backgroundColor: colors.green,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  rowText: { flex: 1, minWidth: 0, gap: spacing.optical },
  rowTitle: { flexShrink: 1, color: colors.text, ...typeScale.body, fontWeight: typeWeight.medium },
  rowSubtitle: { color: colors.textMuted, ...typeScale.label, fontVariant: ["tabular-nums"] },
  menuAnchor: { width: touchTarget, height: touchTarget },
  profileError: {
    marginLeft: controlSize.regular + spacing.sm,
    marginRight: spacing.md,
    marginBottom: spacing.xxs,
    color: colors.red,
    ...typeScale.label,
  },
  profileUnavailable: { color: colors.amber },
  webActions: {
    height: controlSize.regular,
    flexDirection: "row",
    justifyContent: "flex-end",
    paddingHorizontal: spacing.sm,
  },
  smallAction: {
    minHeight: controlSize.regular,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
  },
  smallActionText: { color: colors.textMuted, ...typeScale.label },
  formContent: { padding: spacing.sm, gap: spacing.xs },
  fieldLabel: { color: colors.textMuted, ...typeScale.label },
  textInput: {
    minHeight: touchTarget,
    borderRadius: radii.selected,
    backgroundColor: colors.surfaceContainerLow,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  formGroup: {
    marginTop: spacing.xs,
    overflow: "hidden",
    borderRadius: radii.selected,
    backgroundColor: colors.surfaceContainerLow,
  },
  portField: {
    minHeight: layoutSize.row,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  portInput: {
    width: 82,
    minHeight: touchTarget,
    color: colors.text,
    textAlign: "right",
    fontVariant: ["tabular-nums"],
    paddingVertical: spacing.xs,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    marginLeft: spacing.sm,
    backgroundColor: colors.borderSoft,
  },
  switchRow: {
    minHeight: layoutSize.row,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  inlineError: {
    minHeight: touchTarget,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  errorText: { flex: 1, color: colors.red, ...typeScale.label },
  formActions: {
    minHeight: touchTarget,
    marginTop: spacing.sm,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: spacing.xs,
  },
  primaryButton: {
    minWidth: controlSize.touch,
    minHeight: touchTarget,
    paddingVertical: spacing.xxs,
    paddingHorizontal: spacing.sm,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.large,
    backgroundColor: colors.primary,
  },
  primaryText: { color: colors.onPrimary, ...typeScale.body },
  removeButton: {
    minHeight: touchTarget,
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
  },
  removeText: { color: colors.red, ...typeScale.body },
  rowPressed: { backgroundColor: colors.surfaceHover },
  pressed: { opacity: 0.64 },
});
