import type { ThreadListNavigation } from "../../services/threads/threadNavigationService";
import type { ReactNode } from "react";
import type { ServerScope } from "../../services/servers/serverScope";
import type { ThreadListServer } from "../connections/connectionPresentation";
import type { ThreadListFilter } from "./threadListFilters";
import type { SidebarProjectsNavigation, ThreadListMode } from "./threadListModel";
import type { ThreadListItem } from "./threadListTypes";
import type { GlobalVoiceControl } from "./GlobalVoiceEntryAction";

/** Thread-list data and navigation actions used by the compact mobile surface. */
export type MobileThreadsProps = {
  archivedThreads: ThreadListItem[];
  filter: ThreadListFilter;
  globalVoice: GlobalVoiceControl;
  headerVisible?: boolean;
  initialOffset: number;
  mode: ThreadListMode;
  onArchive: (thread: ThreadListItem) => Promise<void>;
  onFilterChange: (filter: ThreadListFilter) => void;
  onLoadMore: () => Promise<boolean>;
  onManageTerminals: () => void;
  onModeChange: (mode: ThreadListMode) => void;
  onNewThread: () => void;
  onOffsetChange: (offset: number) => void;
  onOpenSearch: () => void;
  onQueryChange: (query: string) => void;
  onRefreshAccountRateLimits?: () => Promise<unknown>;
  onSelectServer: (scope: ServerScope) => void;
  onSettings: () => void;
  onTogglePin: (thread: ThreadListItem) => Promise<void>;
  onToggleRead: (thread: ThreadListItem) => Promise<void>;
  onUnarchive: (thread: ThreadListItem) => Promise<void>;
  query: string;
  searchContent: ReactNode;
  selectedThreadKey?: string | null;
  servers: ThreadListServer[];
  serverScope: ServerScope;
  threadNavigation: ThreadListNavigation;
  threads: ThreadListItem[];
} & SidebarProjectsNavigation;
