import type { ReactNode } from "react";
import type { ThreadListServer } from "../connections/connectionPresentation";
import type { ThreadNavigationModel } from "../navigation/threadNavigation";
import type { ThreadListFilter } from "./threadListFilters";
import type { SidebarProjectsNavigation, ThreadListMode } from "./threadListModel";
import type { ThreadListItem } from "./threadListTypes";
export type ThreadSidebarProps = {
  width: number;
  initialOffset: number;
  onOffsetChange(offset: number): void;
  servers: ThreadListServer[];
  activeServerId: string;
  threads: ThreadListItem[];
  archivedThreads: ThreadListItem[];
  mode: ThreadListMode;
  filter: ThreadListFilter;
  navigation: ThreadNavigationModel;
  onOpenSearch(): void;
  searchContent: ReactNode;
  onModeChange(mode: ThreadListMode): void;
  onFilterChange(filter: ThreadListFilter): void;
  onLoadMore(): void;
  onSelect(id: string): void;
  onPreload(id: string): (() => void) | undefined;
  onSelectServer(id: string): void;
  onSettings(): void;
  onNewThread(): void;
  onTogglePin(thread: ThreadListItem): Promise<void>;
  onArchive(thread: ThreadListItem): Promise<void>;
  onUnarchive(thread: ThreadListItem): Promise<void>;
  onMarkRead(thread: ThreadListItem): Promise<void>;
  onRefreshAccountRateLimits?(): Promise<unknown>;
} & SidebarProjectsNavigation;
