import { StyleSheet } from "react-native";
import { colors, radii, spacing, typeScale } from "../../theme";
import { threadListLayout } from "../../ui/thread-list-layout";
import { THREAD_LIST_ROW_CONTENT_HEIGHT, THREAD_LIST_ROW_VERTICAL_MARGIN } from "./threadListModel";

export const styles = StyleSheet.create({
  pressed: { opacity: 0.68 },
  threadRow: {
    minWidth: 0,
    maxWidth: "100%",
    height: THREAD_LIST_ROW_CONTENT_HEIGHT,
    alignSelf: "stretch",
    marginHorizontal: threadListLayout.edgeInset,
    marginVertical: THREAD_LIST_ROW_VERTICAL_MARGIN,
    paddingVertical: spacing.compact,
    paddingHorizontal: spacing.xs,
    borderRadius: radii.selected,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    position: "relative",
  },
  threadContextMenu: {
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    alignSelf: "stretch",
    flexShrink: 1,
  },
  threadRowSwipeChild: {
    marginHorizontal: 0,
    marginVertical: 0,
    borderRadius: radii.selected,
    backgroundColor: colors.threadListSurface,
  },
  swipeContainer: {
    minWidth: 0,
    maxWidth: "100%",
    alignSelf: "stretch",
    marginHorizontal: threadListLayout.edgeInset,
    marginVertical: THREAD_LIST_ROW_VERTICAL_MARGIN,
    borderRadius: radii.selected,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  swipeChildren: {
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    alignSelf: "stretch",
    backgroundColor: "transparent",
  },
  threadRowSelected: { backgroundColor: colors.secondaryContainer },
  selectionBar: { display: "none" },
  threadText: {
    flex: 1,
    minWidth: 0,
    maxWidth: "100%",
    gap: spacing.optical,
  },
  threadTitleLine: {
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  threadServerEmoji: { ...typeScale.emoji },
  threadTitleSlot: {
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
  },
  threadStatusIcon: {
    width: 18,
    height: 18,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  threadMeta: {
    flexShrink: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xxs,
  },
  threadTime: {
    flexShrink: 0,
    color: colors.textMuted,
    ...typeScale.caption,
    textAlign: "right",
    fontVariant: ["tabular-nums"],
  },
  unreadSlot: {
    width: 7,
    height: 18,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  unreadDot: {
    width: 7,
    height: 7,
    flexShrink: 0,
    borderRadius: radii.pill,
    backgroundColor: colors.primary,
  },
  threadPreviewLine: {
    width: "100%",
    minWidth: 0,
    maxWidth: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  threadPreview: {
    minWidth: 0,
    maxWidth: "100%",
    flex: 1,
    flexShrink: 1,
    color: colors.textMuted,
    ...typeScale.label,
  },
  sheetTitle: {
    minWidth: 0,
    flexShrink: 1,
    color: colors.text,
    ...typeScale.heading,
  },
});
